#include "test/compiler/AutoGenerated.h"

#include <fstream>

AutoGenerated::AutoGenerated(std::string& model)
    : model(model), Network("autogen", "") {
  // Open the file
  std::string filePath = "test/compiler/networks/" + model + "/params.pb";
  std::fstream input(filePath, std::ios::in | std::ios::binary);
  if (!input) {
    std::cerr << "Failed to open " << filePath << std::endl;
    exit(1);
  }

  // Read the proto
  if (!modelParams.ParseFromIstream(&input)) {
    std::cerr << "Failed to parse " << filePath << std::endl;
    exit(1);
  }
}

Workload AutoGenerated::createWorkload(const example::AcceleratorParam& param) {
  Workload workload;
  SimplifiedParams simplifiedParams;

  workload.name = param.name();

  if (param.has_matrix_param()) {
    example::MatrixParam matrixParam = param.matrix_param();

    // input shape = (B, C, H, W)
    // weight shape = (OC, IC, KH, KW)
    int IC = matrixParam.input().shape(1);
    int IH = matrixParam.input().shape(2);
    int IW = matrixParam.input().shape(3);
    int OC = matrixParam.weight().shape(0);
    int KH = matrixParam.weight().shape(2);
    int KW = matrixParam.weight().shape(3);
    int STRIDE = matrixParam.stride(0);

    int inputSize = IH * IW * IC;
    int weightSize = KH * KW * IC * OC;
    int outputSize = (IH / STRIDE) * (IW / STRIDE) * OC;
    int biasSize = OC * 2;
    int residualSize = (IH / STRIDE) * (IW / STRIDE) * OC;

    // TODO: loop tilings are hardcoded for now, ideally we would integrate with
    // a DSE tool like Interstellar

    if (IH == 224 && IW == 224 && IC == 3 && KH == 7 && KW == 7 &&
        OC == 64) {  // conv1
      SimplifiedParams tilingParams = {
          .loops = {{7, 7, 2, 1, 1, 1}, {1, 2, 7, 2, 16, 16}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5},
          .REPLICATION = true};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 64) {  // layer1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 1 && KW == 1 &&
               OC == 64) {  // layer1_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 1, 1, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 1 && KW == 1 &&
               OC == 256) {  // layer1_x_conv3
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 16, 1, 1, 1}, {4, 1, 1, 1, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 256 && KH == 1 && KW == 1 &&
               OC == 64) {  // layer1_x_conv1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {16, 1, 1, 1, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 1 && KW == 1 &&
               OC == 128) {  // layer2_0_downsample (resnet18)
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {4, 2, 1, 1, 14, 14}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 256 && KH == 1 && KW == 1 &&
               OC == 512) {  // layer2_0_downsample (resnet50)
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 16, 1, 1, 1}, {16, 2, 1, 1, 14, 14}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 128 && STRIDE == 2) {  // layer2_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{4, 4, 4, 1, 1, 1}, {4, 3, 3, 2, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 128 && KH == 3 && KW == 3 &&
               OC == 128) {  // layer2
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 256 && KH == 1 && KW == 1 &&
               OC == 128 && STRIDE == 1) {  // layer2_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 8, 1, 1, 1}, {16, 1, 1, 1, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 512 && KH == 1 && KW == 1 &&
               OC == 128) {  // layer2_x_conv1
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {32, 1, 1, 1, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 128 && KH == 3 && KW == 3 &&
               OC == 128) {  // layer2_x_conv2
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 128 && KH == 1 && KW == 1 &&
               OC == 512) {  // layer2_x_conv3
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 32, 1, 1, 1}, {8, 1, 1, 1, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 128 && KH == 1 && KW == 1 &&
               OC == 256) {  // layer3_0_downsample (resnet18)
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 2, 1, 1, 1}, {8, 1, 1, 8, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 512 && KH == 1 && KW == 1 &&
               OC == 1024 && STRIDE == 2) {  // layer3_0_downsample (resnet50)
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 8, 1, 1, 1}, {32, 1, 1, 8, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 128 && KH == 3 && KW == 3 &&
               OC == 256 && STRIDE == 2) {  // layer3_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {8, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 256 && KH == 3 && KW == 3 &&
               OC == 256) {  // layer3_0_conv2
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 512 && KH == 1 && KW == 1 &&
               OC == 256) {  // layer3_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {32, 1, 1, 4, 14, 14}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 1024 && KH == 1 && KW == 1 &&
               OC == 256) {  // layer3_x_conv1
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 4, 1, 1, 1}, {64, 1, 1, 4, 14, 14}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 256 && KH == 3 && KW == 3 &&
               OC == 256) {  // layer3_x_conv2
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 4, 1, 1, 1}, {16, 3, 3, 4, 14, 14}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 256 && KH == 1 && KW == 1 &&
               OC == 1024) {  // layer3_x_conv3
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 16, 1, 1, 1}, {16, 1, 1, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 128) {  // layer3
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {8, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 256 && KH == 1 && KW == 1 &&
               OC == 512 && STRIDE == 2) {  // layer4_0_downsample (resnet18)
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 2, 1, 1, 1}, {16, 1, 1, 16, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 1024 && KH == 1 && KW == 1 &&
               OC == 2048 && STRIDE == 2) {  // layer4_0_downsample (resnet50)
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {64, 1, 1, 16, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 256 && KH == 3 && KW == 3 &&
               OC == 512 && STRIDE == 2) {  // layer4_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 1024 && KH == 1 && KW == 1 &&
               OC == 512 && STRIDE == 1) {  // layer4_0_conv1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 8, 1, 1, 1}, {64, 1, 1, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 7 && IW == 7 && IC == 2048 && KH == 1 && KW == 1 &&
               OC == 512 && STRIDE == 1) {  // layer4_x_conv1
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {128, 1, 1, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 14 && IW == 14 && IC == 512 && KH == 3 && KW == 3 &&
               OC == 512 && STRIDE == 2) {  // layer4_x_conv2
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {32, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 7 && IW == 7 && IC == 512 && KH == 1 && KW == 1 &&
               OC == 2048 ) {  // layer4_x_conv3
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 32, 1, 1, 1}, {32, 1, 1, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 7 && IW == 7 && IC == 512 && KH == 3 && KW == 3 &&
               OC == 512) {  // layer4
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {32, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else {
      std::cout << "Tiling has not been hardcoded for this layer yet"
                << std::endl;
      std::cout << "IH: " << IH << " IW: " << IW << " IC: " << IC
                << " KH: " << KH << " KW: " << KW << " OC: " << OC
                << " STRIDE: " << STRIDE << std::endl;
      exit(1);
    }

    // TODO: use proper offsets. for now, we will just place them contiguously
    simplifiedParams.INPUT_OFFSET = 0;
    simplifiedParams.WEIGHT_OFFSET = inputSize;
    simplifiedParams.BIAS_OFFSET = inputSize + weightSize;
    simplifiedParams.RESIDUAL_OFFSET = inputSize + weightSize + biasSize;
    simplifiedParams.OUTPUT_OFFSET =
        inputSize + weightSize + biasSize + residualSize;

    assert(matrixParam.stride_size() == 1 ||
           matrixParam.stride()[0] == matrixParam.stride()[1]);
    simplifiedParams.STRIDE = matrixParam.stride()[0];

    workload.files.inputs_file = "test/compiler/networks/" + model +
                                 "/tensor_files/" + matrixParam.input().node() +
                                 ".bin";
    workload.files.weights_file = "test/compiler/networks/" + model +
                                  "/tensor_files/" +
                                  matrixParam.weight().node() + ".bin";
    if (matrixParam.has_bias()) {
      workload.files.bias_file = "test/compiler/networks/" + model +
                                 "/tensor_files/" + matrixParam.bias().node() +
                                 ".bin";
      simplifiedParams.BIAS = true;
    }

    workload.memoryMap.inputs = SRAM;
    workload.memoryMap.weights = SRAM;
    workload.memoryMap.bias =
        RRAM;  // TODO: this is hardcoded to be RRAM in other places. we should
               // make it configurable
    workload.memoryMap.outputs = SRAM;
    workload.memoryMap.residual = SRAM;

    simplifiedParams.SOFTMAX = false;
    simplifiedParams.FC = false;
    simplifiedParams.NO_NORM = false;
    simplifiedParams.SOFTMAX_GRAD = false;
    simplifiedParams.FC_GRAD = false;
    simplifiedParams.NO_NORM_GRAD = false;
    simplifiedParams.BIAS_GRAD = false;
    simplifiedParams.CROSS_ENTROPY_GRAD = false;
    simplifiedParams.MSE_GRAD = false;
    simplifiedParams.BCE_WITH_LOGITS_GRAD = false;
    simplifiedParams.GRAD_CLIPPING_UNIT_TEST = false;
    simplifiedParams.MERGE_LORA_WEIGHT = false;
    simplifiedParams.QUANTIZE_TO_P8 = false;
    simplifiedParams.WEIGHT_UPDATE = false;
    simplifiedParams.MAX_REDUCE = false;
    simplifiedParams.ELWISE_ADD = false;
    simplifiedParams.WEIGHT_SPLITTING = false;
    simplifiedParams.RELU_GRAD = false;
    simplifiedParams.CONCAT_INPUT = false;
    simplifiedParams.INPUT_TRANSPOSE = false;
    simplifiedParams.CONCAT_WEIGHT = false;
    simplifiedParams.WEIGHT_TRANSPOSE = false;
    simplifiedParams.SPLIT_OUTPUT = false;
    simplifiedParams.GRAD_CLIPPING = false;
    simplifiedParams.MAXPOOL = false;
    simplifiedParams.AVGPOOL = false;
    simplifiedParams.WEIGHT = true;
  }

  for (int i = 0; i < param.vector_params_size(); i++) {
    example::VectorParam vectorParam = param.vector_params(i);

    if (vectorParam.opcode() == "add_") {
      simplifiedParams.RESIDUAL = true;

      // residual file name is either under input() or other()
      // we need to choose the one that is not the same as the name of the
      // matrixParam node
      std::string residualFile =
          vectorParam.input().node() == param.matrix_param().name()
              ? vectorParam.other().node()
              : vectorParam.input().node();
      workload.files.residual_file = "test/compiler/networks/" + model +
                                     "/tensor_files/" + residualFile + ".bin";
    } else if (vectorParam.opcode() == "relu_") {
      simplifiedParams.RELU = true;
    } else {
      std::cerr << "Opcode not supported" << std::endl;
      exit(1);
    }
  }

  workload.files.outputs_file = "test/compiler/networks/" + model +
                                "/tensor_files/" + param.name() + ".bin";

  workload.params = simplifiedParams;

  std::cout << "Workload: " << workload.name << std::endl;
  std::cout << "Inputs: " << workload.files.inputs_file << std::endl;
  std::cout << "Weights: " << workload.files.weights_file << std::endl;
  std::cout << "Outputs: " << workload.files.outputs_file << std::endl;
  if (workload.files.bias_file != "") {
    std::cout << "Bias: " << workload.files.bias_file << std::endl;
  }
  if (workload.files.residual_file != "") {
    std::cout << "Residual: " << workload.files.residual_file << std::endl;
  }
  std::cout << "Stride: " << simplifiedParams.STRIDE << std::endl;
  std::cout << "loops:" << std::endl;
  std::cout << "loops[0][0] = " << simplifiedParams.loops[0][0] << std::endl;
  std::cout << "loops[0][1] = " << simplifiedParams.loops[0][1] << std::endl;
  std::cout << "loops[0][2] = " << simplifiedParams.loops[0][2] << std::endl;
  std::cout << "loops[1][0] = " << simplifiedParams.loops[1][0] << std::endl;
  std::cout << "loops[1][1] = " << simplifiedParams.loops[1][1] << std::endl;
  std::cout << "loops[1][2] = " << simplifiedParams.loops[1][2] << std::endl;
  std::cout << "loops[1][3] = " << simplifiedParams.loops[1][3] << std::endl;
  std::cout << "loops[1][4] = " << simplifiedParams.loops[1][4] << std::endl;
  std::cout << "loops[1][5] = " << simplifiedParams.loops[1][5] << std::endl;
  std::cout << "inputXLoopIndex[0] = " << simplifiedParams.inputXLoopIndex[0]
            << std::endl;
  std::cout << "inputXLoopIndex[1] = " << simplifiedParams.inputXLoopIndex[1]
            << std::endl;
  std::cout << "inputYLoopIndex[0] = " << simplifiedParams.inputYLoopIndex[0]
            << std::endl;
  std::cout << "inputYLoopIndex[1] = " << simplifiedParams.inputYLoopIndex[1]
            << std::endl;
  std::cout << "reductionLoopIndex[0] = "
            << simplifiedParams.reductionLoopIndex[0] << std::endl;
  std::cout << "reductionLoopIndex[1] = "
            << simplifiedParams.reductionLoopIndex[1] << std::endl;
  std::cout << "weightLoopIndex[0] = " << simplifiedParams.weightLoopIndex[0]
            << std::endl;
  std::cout << "weightLoopIndex[1] = " << simplifiedParams.weightLoopIndex[1]
            << std::endl;
  std::cout << "fxIndex = " << simplifiedParams.fxIndex << std::endl;
  std::cout << "fyIndex = " << simplifiedParams.fyIndex << std::endl;
  std::cout << "weightReuseIndex[0] = " << simplifiedParams.weightReuseIndex[0]
            << std::endl;
  std::cout << "weightReuseIndex[1] = " << simplifiedParams.weightReuseIndex[1]
            << std::endl;
  std::cout << "REPLICATION = " << simplifiedParams.REPLICATION << std::endl;

  return workload;
}

std::vector<Workload> AutoGenerated::getWorkloadsInRange(
    const std::vector<std::string>& workloadNames) {
  std::vector<Workload> workloads;
  // TODO: make it work for a range of workloads

  std::string workloadName = workloadNames[0];
  for (const example::AcceleratorParam& param : modelParams.params()) {
    if (param.name() == workloadName) {
      workloads.push_back(createWorkload(param));
    }
  }
  return workloads;
}

std::vector<Workload> AutoGenerated::getAllWorkloads() {
  std::vector<Workload> workloads;
  // TODO
  return workloads;
}
