#pragma once

#include "proto/param.pb.h"
#include "test/common/Network.h"
#include "test/common/VerificationTypes.h"

class AutoGenerated {
 public:
  AutoGenerated(std::string& model);

  std::vector<codegen::AcceleratorParam> get_params(
      const std::vector<std::string>& names);

 private:
  std::string model;
  std::string project_root;
  codegen::ModelParams model_params;

  Workload createWorkload(const codegen::AcceleratorParam& param);
};
