#include "test/compiler/AutoGenerated.h"

#include <google/protobuf/text_format.h>

#include <fstream>

using namespace std;
using namespace google::protobuf;

AutoGenerated::AutoGenerated(std::string& model) : model(model) {
  project_root = std::string(getenv("PROJECT_ROOT"));

  // Open the file
  std::string filename =
      project_root + "/test/compiler/networks/" + model + "/params.txt";
  std::fstream input(filename, ios::in);
  std::stringstream buffer;
  buffer << input.rdbuf();
  std::string text_str = buffer.str();

  if (!TextFormat::ParseFromString(text_str, &model_params)) {
    std::cerr << "Failed to parse text file." << std::endl;
  }
}

std::vector<codegen::AcceleratorParam> AutoGenerated::get_params(
    const std::vector<std::string>& names) {
  std::vector<codegen::AcceleratorParam> params;
  for (const auto& param : model_params.params()) {
    if (std::find(names.begin(), names.end(), param.name()) != names.end()) {
      params.push_back(param);
    }
  }
  if (params.size() == 0) {
    std::cerr << "Param not found" << std::endl;
    exit(1);
  }
  return params;
}
