#pragma once

#include "proto/param.pb.h"
#include "test/common/Network.h"
#include "test/common/VerificationTypes.h"

class AutoGenerated : public Network {
 public:
  AutoGenerated(std::string& model);

  std::vector<Workload> getWorkloadsInRange(
      const std::vector<std::string>&) override;
  std::vector<Workload> getAllWorkloads() override;

  std::vector<example::AcceleratorParam> get_params(
      const std::vector<std::string>& names);

 private:
  example::ModelParams modelParams;
  std::string model;
  std::string projectRoot;

  Workload createWorkload(const example::AcceleratorParam& param);
};