name: 'Checkout Code, Submodules, and LFS'
description: 'Standardized checkout for all jobs using local SSH and skipping smudge'
runs:
  using: "composite"
  steps:
    - name: Fetch Submodules and LFS
      shell: bash
      run: |
        git submodule update --init --recursive
        GIT_LFS_SKIP_SMUDGE=1 git lfs pull --exclude="voyager-compiler/**"
