#pragma once

#include <array>
#include <map>
#include <string>

#include "test/common/VerificationTypes.h"

const SimplifiedParams conv1_params = {
    .INPUT_OFFSET = 45056,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 847872,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{7, 7, 2, 1, 1, 1}, {1, 2, 7, 2, 16, 16}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = true,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 9408,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = true,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_0_conv1_params = {
    .INPUT_OFFSET = 847872,
    .WEIGHT_OFFSET = 9472,
    .OUTPUT_OFFSET = 45056,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 46336,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_0_conv2_params = {
    .INPUT_OFFSET = 45056,
    .WEIGHT_OFFSET = 46400,
    .OUTPUT_OFFSET = 1249280,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 83264,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 847872,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_1_conv1_params = {
    .INPUT_OFFSET = 1249280,
    .WEIGHT_OFFSET = 83328,
    .OUTPUT_OFFSET = 446464,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 120192,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_1_conv2_params = {
    .INPUT_OFFSET = 446464,
    .WEIGHT_OFFSET = 120256,
    .OUTPUT_OFFSET = 1650688,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 157120,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 1249280,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_0_downsample_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 157184,
    .OUTPUT_OFFSET = 847872,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 2, 1, 1, 14, 14}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 165376,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_0_conv1_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 165504,
    .OUTPUT_OFFSET = 446464,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 4, 4, 1, 1, 1}, {4, 2, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 239232,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_0_conv2_params = {
    .INPUT_OFFSET = 446464,
    .WEIGHT_OFFSET = 239360,
    .OUTPUT_OFFSET = 1249280,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 386816,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 847872,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_1_conv1_params = {
    .INPUT_OFFSET = 1249280,
    .WEIGHT_OFFSET = 386944,
    .OUTPUT_OFFSET = 45056,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 534400,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_1_conv2_params = {
    .INPUT_OFFSET = 45056,
    .WEIGHT_OFFSET = 534528,
    .OUTPUT_OFFSET = 1650688,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 681984,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 1249280,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_0_downsample_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 682112,
    .OUTPUT_OFFSET = 847872,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 2, 1, 1, 1}, {8, 8, 1, 1, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 714880,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_0_conv1_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 715136,
    .OUTPUT_OFFSET = 45056,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {8, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 1010048,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_0_conv2_params = {
    .INPUT_OFFSET = 45056,
    .WEIGHT_OFFSET = 1010304,
    .OUTPUT_OFFSET = 1249280,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {16, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 1600128,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 847872,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_1_conv1_params = {
    .INPUT_OFFSET = 1249280,
    .WEIGHT_OFFSET = 4194304,
    .OUTPUT_OFFSET = 446464,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {16, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 4784128,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_1_conv2_params = {
    .INPUT_OFFSET = 446464,
    .WEIGHT_OFFSET = 4784384,
    .OUTPUT_OFFSET = 1650688,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {16, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 5374208,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 1249280,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_0_downsample_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 1600384,
    .OUTPUT_OFFSET = 847872,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 2, 1, 1, 1}, {16, 16, 1, 1, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 1731456,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_0_conv1_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 8388608,
    .OUTPUT_OFFSET = 446464,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {16, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 9568256,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_0_conv2_params = {
    .INPUT_OFFSET = 446464,
    .WEIGHT_OFFSET = 1731968,
    .OUTPUT_OFFSET = 1249280,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {32, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 4091264,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 847872,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_1_conv1_params = {
    .INPUT_OFFSET = 1249280,
    .WEIGHT_OFFSET = 5374464,
    .OUTPUT_OFFSET = 45056,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {32, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 7733760,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_1_conv2_params = {
    .INPUT_OFFSET = 45056,
    .WEIGHT_OFFSET = 9437184,
    .OUTPUT_OFFSET = 446464,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {32, 4, 3, 3, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 11796480,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 1249280,
    .MAXPOOL = false,
    .AVGPOOL = true,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams fc_params = {
    .INPUT_OFFSET = 446464,
    .WEIGHT_OFFSET = 7734272,
    .OUTPUT_OFFSET = 1650688,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {32, 63, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 8246272,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .FC = true,
};

const SimplifiedParams softmax_params = {
    .INPUT_OFFSET = 1650688,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 1651688,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 1008}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 45056,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = true,
};

std::map<std::string, SimplifiedParams> resnetParams{
    {"conv1", conv1_params},
    {"layer1_0_conv1", layer1_0_conv1_params},
    {"layer1_0_conv2", layer1_0_conv2_params},
    {"layer1_1_conv1", layer1_1_conv1_params},
    {"layer1_1_conv2", layer1_1_conv2_params},
    {"layer2_0_downsample", layer2_0_downsample_params},
    {"layer2_0_conv1", layer2_0_conv1_params},
    {"layer2_0_conv2", layer2_0_conv2_params},
    {"layer2_1_conv1", layer2_1_conv1_params},
    {"layer2_1_conv2", layer2_1_conv2_params},
    {"layer3_0_downsample", layer3_0_downsample_params},
    {"layer3_0_conv1", layer3_0_conv1_params},
    {"layer3_0_conv2", layer3_0_conv2_params},
    {"layer3_1_conv1", layer3_1_conv1_params},
    {"layer3_1_conv2", layer3_1_conv2_params},
    {"layer4_0_downsample", layer4_0_downsample_params},
    {"layer4_0_conv1", layer4_0_conv1_params},
    {"layer4_0_conv2", layer4_0_conv2_params},
    {"layer4_1_conv1", layer4_1_conv1_params},
    {"layer4_1_conv2", layer4_1_conv2_params},
    {"fc", fc_params},
    {"softmax", softmax_params}};

std::array<std::string, 22> resnet_order{"conv1",
                                         "layer1_0_conv1",
                                         "layer1_0_conv2",
                                         "layer1_1_conv1",
                                         "layer1_1_conv2",
                                         "layer2_0_downsample",
                                         "layer2_0_conv1",
                                         "layer2_0_conv2",
                                         "layer2_1_conv1",
                                         "layer2_1_conv2",
                                         "layer3_0_downsample",
                                         "layer3_0_conv1",
                                         "layer3_0_conv2",
                                         "layer3_1_conv1",
                                         "layer3_1_conv2",
                                         "layer4_0_downsample",
                                         "layer4_0_conv1",
                                         "layer4_0_conv2",
                                         "layer4_1_conv1",
                                         "layer4_1_conv2",
                                         "fc",
                                         "softmax"};

std::string resnetDataDir = "/sim2/shared/MINOTAUR/nn_data/resnet/";

std::map<std::string, Files> resnetFiles{
    {"conv1", {"conv1_input", "conv1_weight", "conv1_bias", "conv1_comp"}},
    {"layer1_0_conv1",
     {"layer1_0_conv1_input", "layer1_0_conv1_weight", "layer1_0_conv1_bias",
      "layer1_0_conv1_comp"}},
    {"layer1_0_conv2",
     {"layer1_0_conv2_input", "layer1_0_conv2_weight", "layer1_0_conv2_bias",
      "layer1_0_conv2_comp", "conv1_comp"}},
    {"layer1_1_conv1",
     {"layer1_1_conv1_input", "layer1_1_conv1_weight", "layer1_1_conv1_bias",
      "layer1_1_conv1_comp"}},
    {"layer1_1_conv2",
     {"layer1_1_conv2_input", "layer1_1_conv2_weight", "layer1_1_conv2_bias",
      "layer1_1_conv2_comp", "layer1_0_conv2_comp"}},
    {"layer2_0_downsample",
     {"layer2_0_downsample_input", "layer2_0_downsample_weight",
      "layer2_0_downsample_bias", "layer2_0_downsample_comp"}},
    {"layer2_0_conv1",
     {"layer2_0_conv1_input", "layer2_0_conv1_weight", "layer2_0_conv1_bias",
      "layer2_0_conv1_comp"}},
    {"layer2_0_conv2",
     {"layer2_0_conv2_input", "layer2_0_conv2_weight", "layer2_0_conv2_bias",
      "layer2_0_conv2_comp", "layer2_0_downsample_comp"}},
    {"layer2_1_conv1",
     {"layer2_1_conv1_input", "layer2_1_conv1_weight", "layer2_1_conv1_bias",
      "layer2_1_conv1_comp"}},
    {"layer2_1_conv2",
     {"layer2_1_conv2_input", "layer2_1_conv2_weight", "layer2_1_conv2_bias",
      "layer2_1_conv2_comp", "layer2_0_conv2_comp"}},
    {"layer3_0_downsample",
     {"layer3_0_downsample_input", "layer3_0_downsample_weight",
      "layer3_0_downsample_bias", "layer3_0_downsample_comp"}},
    {"layer3_0_conv1",
     {"layer3_0_conv1_input", "layer3_0_conv1_weight", "layer3_0_conv1_bias",
      "layer3_0_conv1_comp"}},
    {"layer3_0_conv2",
     {"layer3_0_conv2_input", "layer3_0_conv2_weight", "layer3_0_conv2_bias",
      "layer3_0_conv2_comp", "layer3_0_downsample_comp"}},
    {"layer3_1_conv1",
     {"layer3_1_conv1_input", "layer3_1_conv1_weight", "layer3_1_conv1_bias",
      "layer3_1_conv1_comp"}},
    {"layer3_1_conv2",
     {"layer3_1_conv2_input", "layer3_1_conv2_weight", "layer3_1_conv2_bias",
      "layer3_1_conv2_comp", "layer3_0_conv2_comp"}},
    {"layer4_0_downsample",
     {"layer4_0_downsample_input", "layer4_0_downsample_weight",
      "layer4_0_downsample_bias", "layer4_0_downsample_comp"}},
    {"layer4_0_conv1",
     {"layer4_0_conv1_input", "layer4_0_conv1_weight", "layer4_0_conv1_bias",
      "layer4_0_conv1_comp"}},
    {"layer4_0_conv2",
     {"layer4_0_conv2_input", "layer4_0_conv2_weight", "layer4_0_conv2_bias",
      "layer4_0_conv2_comp", "layer4_0_downsample_comp"}},
    {"layer4_1_conv1",
     {"layer4_1_conv1_input", "layer4_1_conv1_weight", "layer4_1_conv1_bias",
      "layer4_1_conv1_comp"}},
    {"layer4_1_conv2",
     {"layer4_1_conv2_input", "layer4_1_conv2_weight", "layer4_1_conv2_bias",
      "layer4_1_conv2_comp", "layer4_0_conv2_comp"}},
    {"fc", {"fc_input", "fc_weight", "fc_bias", "fc_comp"}}};

std::map<std::string, MemoryMap> resnetMemoryMap{
    {"conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer1_0_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer1_0_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer1_1_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer1_1_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer2_0_downsample", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer2_0_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer2_0_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer2_1_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer2_1_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer3_0_downsample", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer3_0_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer3_0_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer3_1_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer3_1_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer4_0_downsample", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer4_0_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer4_0_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer4_1_conv1", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"layer4_1_conv2", {SRAM, RRAM, RRAM, SRAM, SRAM}},
    {"fc", {SRAM, RRAM, RRAM, SRAM, SRAM}}};
