#pragma once

#include <array>
#include <map>
#include <string>

#include "test/common/VerificationTypes.h"

int fx = IC_DIMENSION == 16 ? 2 : (IC_DIMENSION == 32 ? 1 : 7);
const SimplifiedParams conv1_params = {
    .INPUT_OFFSET = 131072,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    // .loops = {{7, 7, 2, 1, 1, 1}, {1, 2, 7, 2, 16, 16}},
    .loops = {{7, 7, 2, 1, 1, 1}, {1, 2, 7, fx, 16, 16}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = true,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 9408,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams maxpool_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{56, 56, 1, 1, 1, 1}, {4, 4, 1, 1, 2, 2}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = true,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_0_conv1_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 9536,
    .OUTPUT_OFFSET = 731072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 46400,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_0_conv2_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 46528,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 83392,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 431072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_1_conv1_params = {
    .INPUT_OFFSET = 131072,
    .WEIGHT_OFFSET = 83520,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 120384,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer1_1_conv2_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 120512,
    .OUTPUT_OFFSET = 731072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 157376,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 131072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_0_downsample_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 157504,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {4, 2, 1, 1, 14, 14}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 165696,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_0_conv1_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 165952,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 4, 4, 1, 1, 1}, {4, 3, 3, 2, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 239680,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_0_conv2_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 239936,
    .OUTPUT_OFFSET = 731072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 387392,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 131072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_1_conv1_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 387648,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 535104,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer2_1_conv2_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 535360,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {8, 1, 3, 3, 28, 28}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 682816,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 731072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_0_downsample_params = {
    .INPUT_OFFSET = 131072,
    .WEIGHT_OFFSET = 683072,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 2, 1, 1, 1}, {8, 1, 1, 8, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    // .loops = {{2, 2, 2, 1, 1, 1}, {8, 8, 1, 1, 7, 7}},
    // .inputXLoopIndex = {0, 5},
    // .inputYLoopIndex = {1, 4},
    // .reductionLoopIndex = {3, 0},
    // .weightLoopIndex = {2, 1},
    // .fxIndex = 3,
    // .fyIndex = 2,
    // .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 715840,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_0_conv1_params = {
    .INPUT_OFFSET = 131072,
    .WEIGHT_OFFSET = 716352,
    .OUTPUT_OFFSET = 731072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {8, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 1011264,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_0_conv2_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 1011776,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 1601600,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 431072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_1_conv1_params = {
    .INPUT_OFFSET = 131072,
    .WEIGHT_OFFSET = 1602112,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 2191936,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer3_1_conv2_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 2192448,
    .OUTPUT_OFFSET = 731072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 2, 4, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 2782272,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 131072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_0_downsample_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 2782784,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 2, 1, 1, 1}, {16, 1, 1, 16, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 2913856,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_0_conv1_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 2914880,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 2,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 4094528,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_0_conv2_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 4095552,
    .OUTPUT_OFFSET = 731072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {32, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 6454848,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 131072,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_1_conv1_params = {
    .INPUT_OFFSET = 731072,
    .WEIGHT_OFFSET = 6455872,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {32, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 8815168,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams layer4_1_conv2_params = {
    .INPUT_OFFSET = 431072,
    .WEIGHT_OFFSET = 8816192,
    .OUTPUT_OFFSET = 131072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 8, 1, 1, 1}, {32, 3, 3, 4, 7, 7}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 3},
    .fxIndex = 2,
    .fyIndex = 1,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = true,
    .BIAS = true,
    .BIAS_OFFSET = 11175488,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 731072,
    .MAXPOOL = false,
    .AVGPOOL = true,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
};

const SimplifiedParams fc_params = {
    .INPUT_OFFSET = 131072,
    .WEIGHT_OFFSET = 11176512,
    .OUTPUT_OFFSET = 431072,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {32, 63, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = true,
    .BIAS_OFFSET = 11692608,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = -1,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = true,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0.0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = true,
};

const std::map<std::string, SimplifiedParams> params{
    {"conv1", conv1_params},
    {"maxpool", maxpool_params},
    {"layer1_0_conv1", layer1_0_conv1_params},
    {"layer1_0_conv2", layer1_0_conv2_params},
    {"layer1_1_conv1", layer1_1_conv1_params},
    {"layer1_1_conv2", layer1_1_conv2_params},
    {"layer2_0_downsample", layer2_0_downsample_params},
    {"layer2_0_conv1", layer2_0_conv1_params},
    {"layer2_0_conv2", layer2_0_conv2_params},
    {"layer2_1_conv1", layer2_1_conv1_params},
    {"layer2_1_conv2", layer2_1_conv2_params},
    {"layer3_0_downsample", layer3_0_downsample_params},
    {"layer3_0_conv1", layer3_0_conv1_params},
    {"layer3_0_conv2", layer3_0_conv2_params},
    {"layer3_1_conv1", layer3_1_conv1_params},
    {"layer3_1_conv2", layer3_1_conv2_params},
    {"layer4_0_downsample", layer4_0_downsample_params},
    {"layer4_0_conv1", layer4_0_conv1_params},
    {"layer4_0_conv2", layer4_0_conv2_params},
    {"layer4_1_conv1", layer4_1_conv1_params},
    {"layer4_1_conv2", layer4_1_conv2_params},
    {"fc", fc_params}};

const std::vector<std::string> order{"conv1",
                                     "maxpool",
                                     "layer1_0_conv1",
                                     "layer1_0_conv2",
                                     "layer1_1_conv1",
                                     "layer1_1_conv2",
                                     "layer2_0_downsample",
                                     "layer2_0_conv1",
                                     "layer2_0_conv2",
                                     "layer2_1_conv1",
                                     "layer2_1_conv2",
                                     "layer3_0_downsample",
                                     "layer3_0_conv1",
                                     "layer3_0_conv2",
                                     "layer3_1_conv1",
                                     "layer3_1_conv2",
                                     "layer4_0_downsample",
                                     "layer4_0_conv1",
                                     "layer4_0_conv2",
                                     "layer4_1_conv1",
                                     "layer4_1_conv2",
                                     "fc"};

const std::map<std::string, Files> files{
    {"conv1", {"conv1_input", "conv1_weight", "conv1_bias", "conv1_comp"}},
    {"maxpool", {"conv1_comp", "", "", "maxpool2d_comp"}},
    {"layer1_0_conv1",
     {"layer1_0_conv1_input", "layer1_0_conv1_weight", "layer1_0_conv1_bias",
      "layer1_0_conv1_comp"}},
    {"layer1_0_conv2",
     {"layer1_0_conv2_input", "layer1_0_conv2_weight", "layer1_0_conv2_bias",
      "layer1_0_conv2_comp", "conv1_comp"}},
    {"layer1_1_conv1",
     {"layer1_1_conv1_input", "layer1_1_conv1_weight", "layer1_1_conv1_bias",
      "layer1_1_conv1_comp"}},
    {"layer1_1_conv2",
     {"layer1_1_conv2_input", "layer1_1_conv2_weight", "layer1_1_conv2_bias",
      "layer1_1_conv2_comp", "layer1_0_conv2_comp"}},
    {"layer2_0_downsample",
     {"layer2_0_downsample_input", "layer2_0_downsample_weight",
      "layer2_0_downsample_bias", "layer2_0_downsample_comp"}},
    {"layer2_0_conv1",
     {"layer2_0_conv1_input", "layer2_0_conv1_weight", "layer2_0_conv1_bias",
      "layer2_0_conv1_comp"}},
    {"layer2_0_conv2",
     {"layer2_0_conv2_input", "layer2_0_conv2_weight", "layer2_0_conv2_bias",
      "layer2_0_conv2_comp", "layer2_0_downsample_comp"}},
    {"layer2_1_conv1",
     {"layer2_1_conv1_input", "layer2_1_conv1_weight", "layer2_1_conv1_bias",
      "layer2_1_conv1_comp"}},
    {"layer2_1_conv2",
     {"layer2_1_conv2_input", "layer2_1_conv2_weight", "layer2_1_conv2_bias",
      "layer2_1_conv2_comp", "layer2_0_conv2_comp"}},
    {"layer3_0_downsample",
     {"layer3_0_downsample_input", "layer3_0_downsample_weight",
      "layer3_0_downsample_bias", "layer3_0_downsample_comp"}},
    {"layer3_0_conv1",
     {"layer3_0_conv1_input", "layer3_0_conv1_weight", "layer3_0_conv1_bias",
      "layer3_0_conv1_comp"}},
    {"layer3_0_conv2",
     {"layer3_0_conv2_input", "layer3_0_conv2_weight", "layer3_0_conv2_bias",
      "layer3_0_conv2_comp", "layer3_0_downsample_comp"}},
    {"layer3_1_conv1",
     {"layer3_1_conv1_input", "layer3_1_conv1_weight", "layer3_1_conv1_bias",
      "layer3_1_conv1_comp"}},
    {"layer3_1_conv2",
     {"layer3_1_conv2_input", "layer3_1_conv2_weight", "layer3_1_conv2_bias",
      "layer3_1_conv2_comp", "layer3_0_conv2_comp"}},
    {"layer4_0_downsample",
     {"layer4_0_downsample_input", "layer4_0_downsample_weight",
      "layer4_0_downsample_bias", "layer4_0_downsample_comp"}},
    {"layer4_0_conv1",
     {"layer4_0_conv1_input", "layer4_0_conv1_weight", "layer4_0_conv1_bias",
      "layer4_0_conv1_comp"}},
    {"layer4_0_conv2",
     {"layer4_0_conv2_input", "layer4_0_conv2_weight", "layer4_0_conv2_bias",
      "layer4_0_conv2_comp", "layer4_0_downsample_comp"}},
    {"layer4_1_conv1",
     {"layer4_1_conv1_input", "layer4_1_conv1_weight", "layer4_1_conv1_bias",
      "layer4_1_conv1_comp"}},
    {"layer4_1_conv2",
     {"layer4_1_conv2_input", "layer4_1_conv2_weight", "layer4_1_conv2_bias",
      "layer4_1_conv2_comp", "layer4_0_conv2_comp"}},
    {"fc", {"fc_input", "fc_weight", "fc_bias", "fc_comp"}}};
