#include "test/common/Simulation.h"

#include <algorithm>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>

#include "test/common/GoldModel.h"
#include "test/common/UniversalPosit.h"
#include "test/common/Utils.h"
#include "test/compiler/AutoGenerated.h"
#include "test/mobilebert/MobileBERT.h"
#include "test/resnet/ResNet.h"

#if __has_include(<filesystem>)
#include <filesystem>
#else
#include <experimental/filesystem>
namespace std {
namespace filesystem = experimental::filesystem;
}
#endif

Simulation::Simulation() {
  modelName = get_env_var("NETWORK");
  if (modelName.empty()) modelName = "resnet";

  tests = get_env_var("TESTS");
  if (tests.empty()) tests = "fc";

  std::string simsEnv(get_env_var("SIMS"));
  if (simsEnv.empty()) simsEnv = "accelerator,customposit,customfloat";

  // Only applicable when NETWORK=mobilebert
  task = get_env_var("TASK");
  if (task.empty()) task = "inference";

  std::string tolerance_str(get_env_var("TOLERANCE"));
  if (!tolerance_str.empty()) tolerance = std::stof(tolerance_str);

  // Paths are relative to Makefile
  std::string data_dir(get_env_var("DATA_DIR"));

  out_dir = get_env_var("OUT_DIR");
  if (out_dir.empty()) out_dir = "./test_outputs/";

  // Parse tests to run
  std::vector<std::string> tests_list;
  split_string(tests, ',', std::back_inserter(tests_list));

  if (tests_list.size() > 2) {
    throw std::runtime_error("Supply at max two TESTS.");
  }

  // Parse sims to run
  split_string(simsEnv, ',', std::back_inserter(sims));
  if (sims.size() & 0x01) {
    throw std::runtime_error("Need to supply even number of sim pairs.");
  }

  // Make "modelName"-matching case insensitive
  std::string modelNameLower = const_cast<std::string&>(this->modelName);
  std::transform(modelNameLower.begin(), modelNameLower.end(),
                 modelNameLower.begin(),
                 [](unsigned char c) { return std::tolower(c); });

  // Match the model family and construct required network
  Network* network;

  // autogenerated models are called "codegen-modelname"
  if (modelNameLower.find("codegen") != std::string::npos) {
    // split modelnameLC at '-' and take the second part
    std::string model = modelNameLower.substr(modelNameLower.find('-') + 1);
    network = new AutoGenerated(model);
  } else {
    if (modelNameLower.find("resnet") != std::string::npos) {
      if (data_dir.empty()) {
        network = new ResNet(modelName);
      } else {
        network = new ResNet(modelName, data_dir);
      }
    } else if (modelNameLower.find("mobilebert") != std::string::npos) {
      if (data_dir.empty()) {
        network = new MobileBERT(modelName, task);
      } else {
        network = new MobileBERT(modelName, task, data_dir);
      }
    } else {
      throw std::runtime_error("Unknown model: " + modelName);
    }
  }

  // Override opt level present in the modelName using the OPT env var, if
  // present. Makes it possible to run the same model with different opt levels
  std::string opt(get_env_var("OPT_LEVEL"));
  if (!opt.empty()) {
    if (opt == "O0") {
      network->opt = Network::O0;
    } else if (opt == "O1") {
      network->opt = Network::O1;
    } else if (opt == "O2") {
      network->opt = Network::O2;
    } else {
      throw std::runtime_error("Unknown opt level: " + opt);
    }
  }

  // Collect workloads (aka. layers) from Network
  workloads = network->getWorkloadsInRange(tests_list);
  params = network->get_params(tests_list);

  std::cout << "Starting new simulation with config:";
  std::cout << "\n> Model: " << modelName;
  std::cout << "\n> Tests: ";
  for (const std::string& l : tests_list) std::cout << l << ' ';
  std::cout << "\n> Sims: ";
  for (const std::string& s : sims) std::cout << s << ' ';
  if (modelNameLower.find("mobilebert") != std::string::npos)
    std::cout << "\n> Task: " << task;
  std::cout << "\n> Tolerance: " << tolerance;
  std::cout << "\n> Data dir: " << network->getDataDir();
  std::cout << "\n> Out dir: " << out_dir << "\n";
  std::cout << "> SRAM: " << SRAM_MEMORY_SIZE / 1024 << " KB\n";
  std::cout << "> RRAM: " << RRAM_MEMORY_SIZE / 1024 << " KB\n";
  std::cout << "> Opt level: " << network->optToString() << std::endl;
}

void Simulation::loadMemory() {
  if (std::find(sims.begin(), sims.end(), "accelerator") != sims.end()) {
    memory_models["accelerator"] = new SimpleMemoryModel<INPUT_DATATYPE>(true);
  }
  // TODO: don't use customposit/customfloat anymore. It should instead be
  // called "hlstype"
  if (std::find(sims.begin(), sims.end(), "customposit") != sims.end()) {
    memory_models["customposit"] = new SimpleMemoryModel<INPUT_DATATYPE>(false);
  }
  if (std::find(sims.begin(), sims.end(), "customfloat") != sims.end()) {
    memory_models["customfloat"] = new SimpleMemoryModel<INPUT_DATATYPE>(false);
  }
  if (std::find(sims.begin(), sims.end(), "universal") != sims.end()) {
    memory_models["universal"] = new SimpleMemoryModel<UniversalPosit>(false);
  }
  if (std::find(sims.begin(), sims.end(), "fp32") != sims.end()) {
    memory_models["fp32"] = new SimpleMemoryModel<float>(false);
  }

  // Load first tests input
  for (const auto& [key, model] : memory_models) {
    model->loadModelActivations(workloads.front().params,
                                workloads.front().files,
                                workloads.front().memoryMap, true);
  }

  // Load weights, biases for all layers
  for (const auto& [key, model] : memory_models) {
    for (const Workload& workload : workloads) {
      if (workload.loadWeight) {
        model->loadModelParams(workload.params, workload.files,
                               workload.memoryMap, true);
      }
    }
  }

  // Load last layer reference outputs
  for (const auto& [key, model] : memory_models) {
    Workload workload = workloads.back();
    model->loadReferenceOutput(workload.params, workload.files,
                               workload.params.ACC_T_OUTPUT);
  }

  // new memory models for pytorch models
  std::vector<int> memory_sizes{SRAM_MEMORY_SIZE, RRAM_MEMORY_SIZE,
                                REFERENCE_MEMORY_SIZE};
  if (std::find(sims.begin(), sims.end(), "posit_pt2e") != sims.end()) {
    memories["posit"] =
        new PyTorchMemoryModelImpl<INPUT_DATATYPE>(memory_sizes, false);
  }
  if (std::find(sims.begin(), sims.end(), "fp32_pt2e") != sims.end()) {
    memories["fp32"] = new PyTorchMemoryModelImpl<float>(memory_sizes, false);
  }
  if (std::find(sims.begin(), sims.end(), "accelerator_pt2e") != sims.end()) {
    memories["accelerator"] =
        new PyTorchMemoryModelImpl<INPUT_DATATYPE>(memory_sizes, false);
  }

  std::string data_dir = "test/compiler/networks/" +
                         modelName.substr(modelName.find('-') + 1) +
                         "/tensor_files";
  for (const auto& [key, model] : memories) {
    model->load_inputs(params.front(), data_dir);
    model->load_outputs(params.back(), data_dir);
    for (const auto& param : params) {
      model->load_weights(param, data_dir);
    }
  }
}

void Simulation::run() {
  // Run tests in sequence
  int X, Y, C, K, FX, FY, STRIDE;
  for (const Workload& workload : workloads) {
    SimplifiedParams params = workload.params;
    MemoryMap memoryMap = workload.memoryMap;

    // Check if mapping valid
    if (validateMapping(params) != 0) {
      std::abort();
    }

    X = params.loops[0][params.inputXLoopIndex[0]] *
        params.loops[1][params.inputXLoopIndex[1]];
    Y = params.loops[0][params.inputYLoopIndex[0]] *
        params.loops[1][params.inputYLoopIndex[1]];
    C = params.loops[1][params.reductionLoopIndex[1]] * (16);
    K = params.loops[0][params.weightLoopIndex[0]] *
        params.loops[1][params.weightLoopIndex[1]] * (16);
    FX = params.loops[1][params.fxIndex];
    FY = params.loops[1][params.fyIndex];
    STRIDE = params.STRIDE;

    if (params.REPLICATION) {
      FX = 7;
      C = 3;
    }

    if (params.MAXPOOL) {
      X /= 2;
      Y /= 2;
    }

    if (params.AVGPOOL) {
      X = 1;
      Y = 1;
    }

    std::cout << "Performing " + workload.name + ":" << std::endl;
    std::cout << "(" << X << "x" << Y << "x" << C << ")" << " * " << "(" << FX
              << "x" << FY << "x" << C << "x" << K << ")" << std::endl;

    // Run gold models
    if (std::find(sims.begin(), sims.end(), "customposit") != sims.end()) {
      auto posit_mem = static_cast<SimpleMemoryModel<INPUT_DATATYPE>*>(
          memory_models["customposit"]);
      auto posit_sram = posit_mem->sram;
      auto posit_rram = posit_mem->rram;
      auto weight_mem = memoryMap.weights ? posit_rram : posit_sram;
      auto bias_mem = params.ATTENTION_MASK ? posit_sram : posit_rram;
      run_gold_model(
          params, posit_sram + params.INPUT_OFFSET,
          weight_mem + params.WEIGHT_OFFSET, posit_sram + params.OUTPUT_OFFSET,
          bias_mem + params.BIAS_OFFSET, posit_sram + params.RESIDUAL_OFFSET,
          posit_sram + params.WEIGHT_RESIDUAL_OFFSET);
    }
    if (std::find(sims.begin(), sims.end(), "customfloat") != sims.end()) {
      auto hls_float_mem = static_cast<SimpleMemoryModel<INPUT_DATATYPE>*>(
          memory_models["customfloat"]);
      auto float_sram = hls_float_mem->sram;
      auto float_rram = hls_float_mem->rram;
      auto weight_mem = memoryMap.weights ? float_rram : float_sram;
      auto bias_mem = params.ATTENTION_MASK ? float_sram : float_rram;
      run_gold_model(
          params, float_sram + params.INPUT_OFFSET,
          weight_mem + params.WEIGHT_OFFSET, float_sram + params.OUTPUT_OFFSET,
          bias_mem + params.BIAS_OFFSET, float_sram + params.RESIDUAL_OFFSET,
          float_sram + params.WEIGHT_RESIDUAL_OFFSET);
    }
    if (std::find(sims.begin(), sims.end(), "universal") != sims.end()) {
      auto universal_mem = static_cast<SimpleMemoryModel<UniversalPosit>*>(
          memory_models["universal"]);
      auto universal_sram = universal_mem->sram;
      auto universal_rram = universal_mem->rram;
      auto weight_mem = memoryMap.weights ? universal_rram : universal_sram;
      auto bias_mem = params.ATTENTION_MASK ? universal_sram : universal_rram;
      run_gold_model(params, universal_sram + params.INPUT_OFFSET,
                     weight_mem + params.WEIGHT_OFFSET,
                     universal_sram + params.OUTPUT_OFFSET,
                     bias_mem + params.BIAS_OFFSET,
                     universal_sram + params.RESIDUAL_OFFSET,
                     universal_sram + params.WEIGHT_RESIDUAL_OFFSET);
    }
    if (std::find(sims.begin(), sims.end(), "fp32") != sims.end()) {
      auto fp32_mem =
          static_cast<SimpleMemoryModel<float>*>(memory_models["fp32"]);
      auto fp32_sram = fp32_mem->sram;
      auto fp32_rram = fp32_mem->rram;
      auto weight_mem = memoryMap.weights ? fp32_rram : fp32_sram;
      auto bias_mem = params.ATTENTION_MASK ? fp32_sram : fp32_rram;
      run_gold_model(
          params, fp32_sram + params.INPUT_OFFSET,
          weight_mem + params.WEIGHT_OFFSET, fp32_sram + params.OUTPUT_OFFSET,
          bias_mem + params.BIAS_OFFSET, fp32_sram + params.RESIDUAL_OFFSET,
          fp32_sram + params.WEIGHT_RESIDUAL_OFFSET);
    }

    if (std::find(sims.begin(), sims.end(), "fp32_pt2e") != sims.end()) {
      auto memory = (PyTorchMemoryModelImpl<float>*)(memories["fp32"]);
      std::vector<float*> args = memory->get_args(this->params[0]);
      run_pytorch_model(this->params[0], args);
    }

    if (std::find(sims.begin(), sims.end(), "posit_pt2e") != sims.end()) {
      auto memory =
          (PyTorchMemoryModelImpl<INPUT_DATATYPE>*)(memories["posit"]);
      std::vector<INPUT_DATATYPE*> args = memory->get_args(this->params[0]);
      run_pytorch_model(this->params[0], args);
    }
  }

  // Run accelerator
  if (std::find(sims.begin(), sims.end(), "accelerator") != sims.end()) {
    auto model = static_cast<SimpleMemoryModel<INPUT_DATATYPE>*>(
        memory_models["accelerator"]);
    std::vector<SimplifiedParams> params_list;
    std::vector<MemoryMap> memoryMap;

    for (const Workload& workload : workloads) {
      params_list.push_back(workload.params);
      memoryMap.push_back(workload.memoryMap);
    }

    run_op(params_list, model->sram, model->rram, memoryMap);
  }

  if (std::find(sims.begin(), sims.end(), "accelerator_pt2e") != sims.end()) {
    auto memory =
        (PyTorchMemoryModelImpl<INPUT_DATATYPE>*)(memories["accelerator"]);
    run_pytorch_op(this->params, memory->memories[0], memory->memories[1]);
  }
}

template <typename T>
SimpleMemoryModel<T>* get_memory(
    const std::vector<std::string>& sims, const std::string& key,
    std::map<std::string, MemoryModel*>& memory_models) {
  if (std::find(sims.begin(), sims.end(), key) == sims.end()) {
    return nullptr;
  }

  return static_cast<SimpleMemoryModel<T>*>(memory_models[key]);
};

int Simulation::checkOutput() {
  SimplifiedParams params = workloads.back().params;
  MemoryMap memoryMaps = workloads.back().memoryMap;

  int X, Y, C, K, FX, FY, STRIDE;
  X = params.loops[0][params.inputXLoopIndex[0]] *
      params.loops[1][params.inputXLoopIndex[1]];
  Y = params.loops[0][params.inputYLoopIndex[0]] *
      params.loops[1][params.inputYLoopIndex[1]];
  C = params.loops[1][params.reductionLoopIndex[1]] * (16);
  K = params.loops[0][params.weightLoopIndex[0]] *
      params.loops[1][params.weightLoopIndex[1]] * (16);
  FX = params.loops[1][params.fxIndex];
  FY = params.loops[1][params.fyIndex];
  STRIDE = params.STRIDE;

  if (params.REPLICATION) {
    FX = 7;
    C = 3;
  }

  if (params.MAXPOOL) {
    X /= 2;
    Y /= 2;
  }

  if (params.AVGPOOL) {
    X = 1;
    Y = 1;
  }

  size_t size = X * Y * K;

  if (params.SOFTMAX || params.SOFTMAX_GRAD) {
    size = X * Y;
  } else if (params.CROSS_ENTROPY_GRAD) {
    size = X;
  } else if (params.NO_NORM_GRAD) {
    size = C;
  } else if (params.WEIGHT_UPDATE) {
    size = X * C;
  }

  std::string outFilePrefix;
  if (workloads.size() == 1) {
    outFilePrefix = out_dir + modelName + '.' + workloads.front().name + '.';
  } else {
    outFilePrefix = out_dir + modelName + '.' + workloads.front().name +
                    "_to_" + workloads.back().name + '.';
  }

  double rel_err = 0.0;
  bool any_comparison = false;

  std::cerr << "Input: " << memoryMaps.inputs << std::endl;
  std::cerr << "Weight: " << memoryMaps.weights << std::endl;
  std::cerr << "Output: " << memoryMaps.outputs << std::endl;

  codegen::AcceleratorParam accel_param;
  if (!this->params.empty()) {
    accel_param = this->params.back();
    auto output = accel_param.output();
    size = 1;
    for (int i = 0; i < output.shape_size(); i++) {
      size *= output.shape(i);
    }
  }

  auto accelerator_memory =
      get_memory<INPUT_DATATYPE>(sims, "accelerator", memory_models);
  auto customposit_memory =
      get_memory<INPUT_DATATYPE>(sims, "customposit", memory_models);
  auto customfloat_memory =
      get_memory<INPUT_DATATYPE>(sims, "customfloat", memory_models);
  auto universal_memory =
      get_memory<UniversalPosit>(sims, "universal", memory_models);
  auto fp32_memory = get_memory<float>(sims, "fp32", memory_models);

  bool file = std::find(sims.begin(), sims.end(), "file") != sims.end();

  auto fp32_pt2e_memory =
      static_cast<PyTorchMemoryModelImpl<float>*>(memories["fp32"]);
  auto posit_pt2e_memory =
      static_cast<PyTorchMemoryModelImpl<INPUT_DATATYPE>*>(memories["posit"]);
  auto accelerator_pt2e_memory =
      static_cast<PyTorchMemoryModelImpl<INPUT_DATATYPE>*>(
          memories["accelerator"]);

  if (fp32_memory && file) {
    std::cout << "FP32 Gold Model vs. Pytorch" << std::endl;
    std::cout << "(reveals issues in data loading or mapping)" << std::endl;
    std::string diffFile = outFilePrefix + "fpgold_vs_pytorch.txt";

    rel_err += compare_arrays(fp32_memory->sram + params.OUTPUT_OFFSET, "fp32",
                              fp32_memory->reference, "file", size, diffFile,
                              params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (customposit_memory && file) {
    std::cout << "HLS Posit Gold Model vs. Pytorch" << std::endl;
    std::cout << "(reveals bugs in mapping operations to accelerator)"
              << std::endl;
    std::string diffFile = outFilePrefix + "hlsgold_vs_pytorch.txt";

    rel_err += compare_arrays(customposit_memory->sram + params.OUTPUT_OFFSET,
                              "customposit", customposit_memory->reference,
                              "file", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (universal_memory && file) {
    std::cout << "Universal Posit Gold Model vs. Pytorch" << std::endl;
    std::cout << "(reveals issues in representing float as Posit)" << std::endl;
    std::string diffFile = outFilePrefix + "universal_vs_pytorch.txt";

    rel_err += compare_arrays(universal_memory->sram + params.OUTPUT_OFFSET,
                              "universal", universal_memory->reference, "file",
                              size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (accelerator_memory && file) {
    std::cout << "Accelerator vs. PyTorch" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_pytorch.txt";

    rel_err += compare_arrays(accelerator_memory->sram + params.OUTPUT_OFFSET,
                              "accelerator", accelerator_memory->reference,
                              "file", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (customposit_memory && accelerator_memory) {
    std::cout << "Accelerator vs. HLS Posit Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_hlsgold.txt";

    rel_err += compare_arrays(
        accelerator_memory->sram + params.OUTPUT_OFFSET, "accelerator",
        customposit_memory->sram + params.OUTPUT_OFFSET, "customposit", size,
        diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (customfloat_memory && accelerator_memory) {
    std::cout << "Accelerator vs. HLS custom Float Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_hlsgold.txt";

    rel_err += compare_arrays(
        accelerator_memory->sram + params.OUTPUT_OFFSET, "accelerator",
        customfloat_memory->sram + params.OUTPUT_OFFSET, "customfloat", size,
        diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (customposit_memory && universal_memory) {
    std::cout << "HLS Posit Gold Model vs. Universal Posit Gold Model"
              << std::endl;
    std::cout
        << "(reveals bugs in implementation of custom HLS Posit operators)"
        << std::endl;
    std::string diffFile = outFilePrefix + "hlsgold_vs_universal.txt";

    rel_err += compare_arrays(customposit_memory->sram + params.OUTPUT_OFFSET,
                              "customposit",
                              universal_memory->sram + params.OUTPUT_OFFSET,
                              "universal", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (customposit_memory && fp32_memory) {
    std::cout << "HLS Posit Gold Model vs. FP32 Gold Model" << std::endl;
    std::cout
        << "(reveals bugs between FP32 and HLS Posit Gold Model implementation)"
        << std::endl;
    std::string diffFile = outFilePrefix + "hlsgold_vs_fpgold.txt";

    rel_err +=
        compare_arrays(customposit_memory->sram + params.OUTPUT_OFFSET,
                       "customposit", fp32_memory->sram + params.OUTPUT_OFFSET,
                       "fp32", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (accelerator_memory && fp32_memory) {
    std::cout << "Accelerator vs. FP32 Gold Model" << std::endl;
    std::cout << "(reveals bugs between Accelerator and FP32 Gold Model "
                 "implementation)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_fpgold.txt";

    rel_err +=
        compare_arrays(accelerator_memory->sram + params.OUTPUT_OFFSET,
                       "accelerator", fp32_memory->sram + params.OUTPUT_OFFSET,
                       "fp32", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  //======================================
  // PT2E Codegen Validation
  //======================================

  if (fp32_pt2e_memory && file) {
    std::cout << "FP32 PyTorch Gold Model vs. Pytorch" << std::endl;
    std::cout << "(reveals issues in data loading or mapping)" << std::endl;
    std::string diffFile = outFilePrefix + "codegen_vs_pytorch.txt";

    rel_err +=
        compare_arrays(fp32_pt2e_memory->get_args(accel_param).back(),
                       "fp32_pt2e", fp32_pt2e_memory->get_output(accel_param),
                       "file", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (accelerator_pt2e_memory && file) {
    std::cout << "Accelerator vs. HLS Posit Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_pytorch.txt";

    rel_err += compare_arrays(
        accelerator_pt2e_memory->get_args(accel_param).back(), "accelerator",
        accelerator_pt2e_memory->get_output(accel_param), "file", size,
        diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (accelerator_pt2e_memory && posit_pt2e_memory) {
    std::cout << "Accelerator vs. HLS Posit Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_hlsgold.txt";

    rel_err += compare_arrays(
        accelerator_pt2e_memory->get_args(accel_param).back(), "accelerator",
        posit_pt2e_memory->get_args(accel_param).back(), "posit_pt2e", size,
        diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  //======================================
  // PT2E Codegen vs. Old Gold Model
  //======================================

  if (fp32_pt2e_memory && fp32_memory) {
    std::cout << "FP32 Gold Model vs. FP32 Codegen Gold Model" << std::endl;
    std::cout << "(reveals issues in data loading or mapping)" << std::endl;
    std::string diffFile = outFilePrefix + "fpgold_vs_codegen.txt";

    rel_err += compare_arrays(fp32_memory->sram + params.OUTPUT_OFFSET, "fp32",
                              fp32_pt2e_memory->get_args(accel_param).back(),
                              "fp32_pt2e", size, diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (posit_pt2e_memory && customposit_memory) {
    std::cout << "Posit Gold Model vs. Posit Codegen Gold Model" << std::endl;
    std::cout << "(reveals issues in data loading or mapping)" << std::endl;
    std::string diffFile = outFilePrefix + "posit_vs_codegen.txt";

    rel_err += compare_arrays(
        customposit_memory->sram + params.OUTPUT_OFFSET, "customposit",
        posit_pt2e_memory->get_args(accel_param).back(), "posit_pt2e", size,
        diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (accelerator_pt2e_memory && customposit_memory) {
    std::cout << "Accelerator vs. HLS Posit Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string diffFile = outFilePrefix + "accel_vs_hlsgold.txt";

    rel_err += compare_arrays(
        accelerator_pt2e_memory->get_args(accel_param).back(), "accelerator",
        customposit_memory->sram + params.OUTPUT_OFFSET, "customposit", size,
        diffFile, params.ACC_T_OUTPUT);
    any_comparison = true;
  }

  if (!any_comparison) {
    std::cout << "No valid comparisons specified" << std::endl;
    std::abort();
  }

  int error_count = 0;
  if (rel_err > tolerance) {
    error_count += rel_err < 1.0 ? 1 : static_cast<int>(rel_err);
  }

  std::cout << "Rela. error: " << rel_err << std::endl;
  std::cout << "Error count: " << error_count << std::endl;

  return error_count;
}

// Iterate over string and return vector of substrings cut at delim
template <typename T>
void Simulation::split_string(const std::string& in_string, char delim,
                              T result) {
  std::istringstream ss(in_string);
  std::string item;
  while (std::getline(ss, item, delim)) {
    *result++ = item;
  }
}

// Return environment variable
std::string Simulation::get_env_var(std::string const& name) {
  const char* val = std::getenv(name.c_str());
  return val == NULL ? std::string() : std::string(val);
}

void Simulation::print_help() {
  std::cout << "\nConfigure simulator by using environment variables."
            << "\n NETWORK - Type of network to run {mobilebert, resnet}"
            << "\n TESTS - Layers in network to run. Either single or tuple: "
               "<first>,<last>."
            << "\n SIMS - Simulators / models to compare {accelerator, "
               "customposit, universal, fp32, file}."
            << "\n TASK - MobileBERT run time (forward, backward, e2e)."
            << "\n TOLERANCE - Relative normalized error in % we allow "
               "(default 10)."
            << "\n DATA_DIR - Path to binary input data."
            << "\n OUT_DIR - Path to output data." << std::endl;
}