#include "test/common/Simulation.h"

#include <algorithm>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>

#include "test/common/GoldModel.h"
#include "test/common/UniversalPosit.h"
#include "test/common/Utils.h"
#include "test/compiler/AutoGenerated.h"
#include "test/mobilebert/MobileBERT.h"
#include "test/resnet/ResNet.h"

#if __has_include(<filesystem>)
#include <filesystem>
#else
#include <experimental/filesystem>
namespace std {
namespace filesystem = experimental::filesystem;
}
#endif

using FloatMemoryModel = PyTorchMemoryModelImpl<float>;
using HlsMemoryModel = PyTorchMemoryModelImpl<INPUT_DATATYPE>;

Simulation::Simulation() {
  model_name = get_env_var("NETWORK");
  if (model_name.empty()) model_name = "resnet";

  tests = get_env_var("TESTS");
  if (tests.empty()) tests = "fc";

  std::string sims_env(get_env_var("SIMS"));
  if (sims_env.empty()) sims_env = "fp32,systemc,accelerator";

  // Only applicable when NETWORK=mobilebert
  task = get_env_var("TASK");
  if (task.empty()) task = "inference";

  std::string tolerance_str(get_env_var("TOLERANCE"));
  if (!tolerance_str.empty()) tolerance = std::stof(tolerance_str);

  // Paths are relative to Makefile
  std::string data_dir(get_env_var("DATA_DIR"));

  out_dir = get_env_var("OUT_DIR");
  if (out_dir.empty()) out_dir = "./test_outputs/";

  // Parse tests to run
  std::vector<std::string> tests_list;
  split_string(tests, ',', std::back_inserter(tests_list));

  if (tests_list.size() > 2) {
    throw std::runtime_error("Supply at max two TESTS.");
  }

  // Parse sims to run
  split_string(sims_env, ',', std::back_inserter(sims));
  if (sims.size() & 0x01) {
    throw std::runtime_error("Need to supply even number of sim pairs.");
  }

  // Make model name-matching case insensitive
  std::string model_name_lower = const_cast<std::string&>(this->model_name);
  std::transform(model_name_lower.begin(), model_name_lower.end(),
                 model_name_lower.begin(),
                 [](unsigned char c) { return std::tolower(c); });

  // Match the model family and construct required network
  auto network = new AutoGenerated(model_name_lower);
  params = network->get_params(tests_list);

  std::cout << "Starting new simulation with config:";
  std::cout << "\n> Model: " << model_name;
  std::cout << "\n> Tests: ";
  for (const std::string& l : tests_list) std::cout << l << ' ';
  std::cout << "\n> Sims: ";
  for (const std::string& s : sims) std::cout << s << ' ';
  if (model_name_lower.find("mobilebert") != std::string::npos)
    std::cout << "\n> Task: " << task;
  std::cout << "\n> Tolerance: " << tolerance;
  // std::cout << "\n> Data dir: " << network->getDataDir();
  std::cout << "\n> Out dir: " << out_dir << "\n";
  std::cout << "> SRAM: " << SRAM_MEMORY_SIZE / 1024 << " KB\n";
  std::cout << "> RRAM: " << RRAM_MEMORY_SIZE / 1024 << " KB\n";
}

void Simulation::load_data() {
  std::vector<int> memory_sizes{SRAM_MEMORY_SIZE, RRAM_MEMORY_SIZE,
                                REFERENCE_MEMORY_SIZE};
  if (std::find(sims.begin(), sims.end(), "fp32") != sims.end()) {
    memories["fp32"] = new FloatMemoryModel(memory_sizes, false);
  }
  if (std::find(sims.begin(), sims.end(), "systemc") != sims.end()) {
    memories["systemc"] = new HlsMemoryModel(memory_sizes, false);
  }
  if (std::find(sims.begin(), sims.end(), "accelerator") != sims.end()) {
    memories["accelerator"] = new HlsMemoryModel(memory_sizes, true);
  }

  std::string data_dir =
      "test/compiler/networks/" + model_name + "/tensor_files";
  for (const auto& [key, model] : memories) {
    model->load_inputs(params.front(), data_dir);
    model->load_outputs(params.back(), data_dir);
    for (const auto& param : params) {
      model->load_weights(param, data_dir);
    }
  }
}

void Simulation::run() {
  // Run gold models
  for (const auto& param : params) {
    if (std::find(sims.begin(), sims.end(), "fp32") != sims.end()) {
      auto memory = (FloatMemoryModel*)(memories["fp32"]);
      auto args = memory->get_args(param);
      run_pytorch_model(param, args);
    }

    if (std::find(sims.begin(), sims.end(), "systemc") != sims.end()) {
      auto memory = (HlsMemoryModel*)(memories["systemc"]);
      auto args = memory->get_args(param);
      run_pytorch_model(param, args);
    }
  }

  // Run accelerator
  if (std::find(sims.begin(), sims.end(), "accelerator") != sims.end()) {
    auto memory = (HlsMemoryModel*)(memories["accelerator"]);
    run_pytorch_op(params, memory->memories[0], memory->memories[1]);
  }
}

int Simulation::check_outputs() {
  std::string prefix;
  if (params.size() == 1) {
    prefix = out_dir + model_name + '.' + params.front().name() + '.';
  } else {
    prefix = out_dir + model_name + '.' + params.front().name() + "_to_" +
             params.back().name() + '.';
  }

  bool has_valid_comp = false;
  double rel_err = 0.0;

  auto param = params.back();
  int size = 1;
  for (const auto& dim : param.output().shape()) size *= dim;

  bool file = std::find(sims.begin(), sims.end(), "file") != sims.end();

  auto fp32_memory = (FloatMemoryModel*)memories["fp32"];
  auto systemc_memory = (HlsMemoryModel*)memories["systemc"];
  auto accelerator_memory = (HlsMemoryModel*)memories["accelerator"];

  if (fp32_memory && file) {
    std::cout << "FP32 PyTorch Gold Model vs. Pytorch" << std::endl;
    std::cout << "(reveals issues in data loading or mapping)" << std::endl;
    std::string filename = prefix + "codegen_vs_pytorch.txt";

    rel_err += compare_arrays(fp32_memory->get_args(param).back(), "fp32",
                              fp32_memory->get_output(param), "file", size,
                              filename, false);
    has_valid_comp = true;
  }

  if (accelerator_memory && file) {
    std::cout << "Accelerator vs. HLS Posit Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string filename = prefix + "accel_vs_pytorch.txt";

    rel_err += compare_arrays(
        accelerator_memory->get_args(param).back(), "accelerator",
        accelerator_memory->get_output(param), "file", size, filename, false);
    has_valid_comp = true;
  }

  if (accelerator_memory && systemc_memory) {
    std::cout << "Accelerator vs. HLS Posit Gold Model" << std::endl;
    std::cout << "(reveals bugs in accelerator or memory placement)"
              << std::endl;
    std::string filename = prefix + "accel_vs_hlsgold.txt";

    rel_err +=
        compare_arrays(accelerator_memory->get_args(param).back(),
                       "accelerator", systemc_memory->get_args(param).back(),
                       "systemc", size, filename, false);
    has_valid_comp = true;
  }

  if (!has_valid_comp) {
    std::cout << "No valid comparisons specified" << std::endl;
    std::abort();
  }

  int error_count = 0;
  if (rel_err > tolerance) {
    error_count += rel_err < 1.0 ? 1 : static_cast<int>(rel_err);
  }

  std::cout << "Rela. error: " << rel_err << std::endl;
  std::cout << "Error count: " << error_count << std::endl;

  return error_count;
}

// Iterate over string and return vector of substrings cut at delim
template <typename T>
void Simulation::split_string(const std::string& in_string, char delim,
                              T result) {
  std::istringstream ss(in_string);
  std::string item;
  while (std::getline(ss, item, delim)) {
    *result++ = item;
  }
}

// Return environment variable
std::string Simulation::get_env_var(std::string const& name) {
  const char* val = std::getenv(name.c_str());
  return val == NULL ? std::string() : std::string(val);
}

void Simulation::print_help() {
  std::cout << "\nConfigure simulator by using environment variables."
            << "\n NETWORK - Type of network to run {mobilebert, resnet}"
            << "\n TESTS - Layers in network to run. Either single or tuple: "
               "<first>,<last>."
            << "\n SIMS - Simulators / models to compare {accelerator, "
               "customposit, universal, fp32, file}."
            << "\n TASK - MobileBERT run time (forward, backward, e2e)."
            << "\n TOLERANCE - Relative normalized error in % we allow "
               "(default 10)."
            << "\n DATA_DIR - Path to binary input data."
            << "\n OUT_DIR - Path to output data." << std::endl;
}
