#pragma once

#include <map>
#include <string>
#include <vector>

#include "test/common/VerificationTypes.h"

std::vector<std::string> backpropOrder{
    "classifier",
    "output_bottleneck_LayerNorm",
    "output_bottleneck_dense",
    "output_LayerNorm",
    "output_dense",
    "intermediate_dense",
    "ffn_0_output_LayerNorm",
    "ffn_0_output_dense",
    "ffn_0_intermediate_dense",
    "attention_output_LayerNorm",
    "attention_output_dense",
    "bottleneck_input_dense",
    "attention_self_context_layer",
    "attention_self_value_layer_3",
    "attention_self_value_layer_2",
    "attention_self_value_layer_1",
    "attention_self_value_layer_0",
    "attention_self_attention_probs_0",
    "attention_self_attention_probs_1",
    "attention_self_attention_probs_2",
    "attention_self_attention_probs_3",
    "attention_self_attention_scores_0",
    "attention_self_attention_scores_1",
    "attention_self_attention_scores_2",
    "attention_self_attention_scores_3",
    "attention_self_query_layer_3",
    "attention_self_query_layer_2",
    "attention_self_query_layer_1",
    "attention_self_query_layer_0",
    "attention_self_key_layer_3",
    "attention_self_key_layer_2",
    "attention_self_key_layer_1",
    "attention_self_key_layer_0",
    "query_to_bottleneck_attention_LayerNorm",
    "key_to_bottleneck_attention_LayerNorm",
    "bottleneck_attention_dense",
    "shared_attention_input_to_hidden_states",
    "value_to_hidden_states",
    "bottlenecked_hidden_states",
};

// (1 x 16)
const SimplifiedParams cross_entropy_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 16}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = true,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_GRADIENT_OFFSET = 0,
    .BIAS_GRADIENT_OFFSET = 0,
    .learningRate = 0.0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = false,
    .outputExpBias = 12,
};

// (128 x 16) x (16 x 512)
const SimplifiedParams classifier_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {1, 32, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
};

// (128 x 512) * 512
const SimplifiedParams output_bottleneck_LayerNorm_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {32, 32, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = true,
};

// (128 x 512) x (512 x 128)
const SimplifiedParams output_bottleneck_dense_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {32, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
};

// (128 x 128) * 128
const SimplifiedParams bottleneck_LayerNorm_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {2, 0},
    .weightLoopIndex = {3, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = true,
};

// (128 x 128) x (128 x 512)
const SimplifiedParams output_dense_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 32, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = true,
};

// (128 x 512) x (512 x 128)
const SimplifiedParams intermediate_dense_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {32, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
};

// (128 x 128) x (128 x 128)
const SimplifiedParams attention_output_dense_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = true,
};

// (128 x 32) * (32 x 128)
const SimplifiedParams context_to_attention_probs = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {2, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
};

// (128 x 128) x (128 x 32)
const SimplifiedParams context_to_value = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 2, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
};

// (128 x 128)
const SimplifiedParams softmax_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 128, 128}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = true,
};

// (128 x 128) x (128 x 32)
const SimplifiedParams attention_score_to_query = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 2, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {5, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = true,
};

// (128 x 128) * (128 x 32)
const SimplifiedParams attention_score_to_key = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 2, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {5, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = true,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
};

// (4 x 128 x 32) x (128 x 128)
const SimplifiedParams query_projection_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {5, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = true,
};

// (4 x 128 x 32) x (128 x 128)
const SimplifiedParams key_projection_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {5, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = true,
};

// (128 x 128) x (128 x 512)
const SimplifiedParams value_projection_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 32, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {5, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = true,
};

// (128 x 128) x (128 x 512)
const SimplifiedParams input_bottleneck_backward = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = true,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 32, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {5, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = true,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = true,
};

std::map<std::string, SimplifiedParams> backpropParams{
    {"classifier", cross_entropy_gradient},
    {"output_bottleneck_LayerNorm", classifier_backward},
    {"output_bottleneck_dense", output_bottleneck_LayerNorm_backward},
    {"output_LayerNorm", output_bottleneck_dense_backward},
    {"output_dense", bottleneck_LayerNorm_backward},
    {"intermediate_dense", output_dense_backward},
    {"ffn_0_output_LayerNorm", intermediate_dense_backward},
    {"ffn_0_output_dense", bottleneck_LayerNorm_backward},
    {"ffn_0_intermediate_dense", output_dense_backward},
    {"attention_output_LayerNorm", intermediate_dense_backward},
    {"attention_output_dense", bottleneck_LayerNorm_backward},
    {"bottleneck_input_dense", bottleneck_LayerNorm_backward},
    {"attention_self_context_layer", attention_output_dense_backward},
    {"attention_self_value_layer_0", context_to_value},
    {"attention_self_value_layer_1", context_to_value},
    {"attention_self_value_layer_2", context_to_value},
    {"attention_self_value_layer_3", context_to_value},
    {"attention_self_attention_probs_0", context_to_attention_probs},
    {"attention_self_attention_probs_1", context_to_attention_probs},
    {"attention_self_attention_probs_2", context_to_attention_probs},
    {"attention_self_attention_probs_3", context_to_attention_probs},
    {"attention_self_attention_scores_0", softmax_gradient},
    {"attention_self_attention_scores_1", softmax_gradient},
    {"attention_self_attention_scores_2", softmax_gradient},
    {"attention_self_attention_scores_3", softmax_gradient},
    {"attention_self_query_layer_0", attention_score_to_query},
    {"attention_self_query_layer_1", attention_score_to_query},
    {"attention_self_query_layer_2", attention_score_to_query},
    {"attention_self_query_layer_3", attention_score_to_query},
    {"attention_self_key_layer_0", attention_score_to_key},
    {"attention_self_key_layer_1", attention_score_to_key},
    {"attention_self_key_layer_2", attention_score_to_key},
    {"attention_self_key_layer_3", attention_score_to_key},
    {"query_to_bottleneck_attention_LayerNorm", query_projection_backward},
    {"key_to_bottleneck_attention_LayerNorm", key_projection_backward},
    {"bottleneck_attention_dense", bottleneck_LayerNorm_backward},
    {"shared_attention_input_to_hidden_states", input_bottleneck_backward},
    {"value_to_hidden_states", value_projection_backward},
    {"bottlenecked_hidden_states", input_bottleneck_backward},
};

std::map<std::string, MemoryOffsets> backpropMemOffsets{
    {"classifier",
     {
         5 * INTERMEDIATE_SIZE + 22 * HIDDEN_SIZE,
         0,
         0,
     }},
    {"output_bottleneck_LayerNorm",
     {
         0,
         8 * WEIGHT_INTERMEDIATE_SIZE + 5 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE,
     }},
    {"output_bottleneck_dense",
     {
         INTERMEDIATE_SIZE,
         8 * WEIGHT_INTERMEDIATE_SIZE + 3 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
         0,
     }},
    {"output_LayerNorm",
     {
         0,
         7 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE,
     }},
    {"output_dense",
     {
         INTERMEDIATE_SIZE,
         7 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 16 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
     }},
    {"intermediate_dense",
     {
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
         6 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 15 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + 20 * HIDDEN_SIZE,
     }},
    {"ffn_0_output_LayerNorm",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         5 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 15 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE,
         0,
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
     }},
    {"ffn_0_output_dense",
     {
         INTERMEDIATE_SIZE,
         5 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 13 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
     }},
    {"ffn_0_intermediate_dense",
     {
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
         4 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 12 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 18 * HIDDEN_SIZE,
     }},
    {"attention_output_LayerNorm",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         3 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             12 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE,
         0,
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
     }},
    {"attention_output_dense",
     {
         INTERMEDIATE_SIZE,
         3 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             10 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
     }},
    {"bottleneck_input_dense",
     {
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
         WEIGHT_INTERMEDIATE_SIZE + BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE,
     }},
    {"attention_self_context_layer",
     {
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
         3 * WEIGHT_INTERMEDIATE_SIZE + 2 * WEIGHT_HIDDEN_SIZE +
             9 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
     }},
    {"attention_self_value_layer_0",
     {
         INTERMEDIATE_SIZE + 11 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
     }},
    {"attention_self_value_layer_1",
     {
         INTERMEDIATE_SIZE + 12 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + HEAD_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE + HEAD_SIZE,
     }},
    {"attention_self_value_layer_2",
     {
         INTERMEDIATE_SIZE + 13 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + 2 * HEAD_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE + 2 * HEAD_SIZE,
     }},
    {"attention_self_value_layer_3",
     {
         INTERMEDIATE_SIZE + 14 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + 3 * HEAD_SIZE,
         INTERMEDIATE_SIZE + HIDDEN_SIZE + 3 * HEAD_SIZE,
     }},
    {"attention_self_attention_probs_0",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
     }},
    {"attention_self_attention_probs_1",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + HEAD_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + HEAD_SIZE,
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
     }},
    {"attention_self_attention_probs_2",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + 2 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + 2 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE,
     }},
    {"attention_self_attention_probs_3",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + 3 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE + 3 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE,
     }},

    {"attention_self_attention_scores_0",
     {
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 11 * HIDDEN_SIZE,
     }},
    {"attention_self_attention_scores_1",
     {
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 12 * HIDDEN_SIZE,
     }},
    {"attention_self_attention_scores_2",
     {
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 13 * HIDDEN_SIZE,
     }},
    {"attention_self_attention_scores_3",
     {
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 14 * HIDDEN_SIZE,
     }},

    {"attention_self_query_layer_0",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE,
     }},
    {"attention_self_query_layer_1",
     {
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE + HEAD_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE + HEAD_SIZE,
     }},
    {"attention_self_query_layer_2",
     {
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE + 2 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE + 2 * HEAD_SIZE,
     }},
    {"attention_self_query_layer_3",
     {
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE + 3 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE + 3 * HEAD_SIZE,
     }},
    {"attention_self_key_layer_0",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 7 * HIDDEN_SIZE,
     }},
    {"attention_self_key_layer_1",
     {
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE + HEAD_SIZE,
         INTERMEDIATE_SIZE + 7 * HIDDEN_SIZE + HEAD_SIZE,
     }},
    {"attention_self_key_layer_2",
     {
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE + 2 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 7 * HIDDEN_SIZE + 2 * HEAD_SIZE,
     }},
    {"attention_self_key_layer_3",
     {
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 5 * HIDDEN_SIZE + 3 * HEAD_SIZE,
         INTERMEDIATE_SIZE + 7 * HIDDEN_SIZE + 3 * HEAD_SIZE,
     }},

    {"query_to_bottleneck_attention_LayerNorm",
     {
         INTERMEDIATE_SIZE + 6 * HIDDEN_SIZE,
         2 * WEIGHT_INTERMEDIATE_SIZE + 6 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
     }},
    {"key_to_bottleneck_attention_LayerNorm",
     {
         INTERMEDIATE_SIZE + 7 * HIDDEN_SIZE,
         2 * WEIGHT_INTERMEDIATE_SIZE + WEIGHT_HIDDEN_SIZE +
             7 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
         0,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
     }},
    {"bottleneck_attention_dense",
     {
         INTERMEDIATE_SIZE + 3 * HIDDEN_SIZE,
         2 * WEIGHT_INTERMEDIATE_SIZE + 4 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
     }},
    {"shared_attention_input_to_hidden_states",
     {
         INTERMEDIATE_SIZE,
         0,
         0,
         0,
         0,
     }},
    {"value_to_hidden_states",
     {
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
         2 * WEIGHT_INTERMEDIATE_SIZE + 2 * WEIGHT_HIDDEN_SIZE +
             8 * BIAS_HIDDEN_SIZE,
         0,
         0,
         0,
     }},
    {"bottlenecked_hidden_states",
     {
         INTERMEDIATE_SIZE + 2 * HIDDEN_SIZE,
         WEIGHT_INTERMEDIATE_SIZE + 3 * BIAS_HIDDEN_SIZE,
         INTERMEDIATE_SIZE,
         0,
         0,
     }},
};

std::map<std::string, Files> backpropTestFiles{
    {"classifier",
     {
         "classifier",
         "mobilebert_labels",
         "",
         "classifier",
     }},
    {"output_bottleneck_LayerNorm",
     {
         "classifier",
         "classifier_weight",
         "",
         "mobilebert_encoder_layer_23_output_bottleneck_LayerNorm",
     }},
    {"output_bottleneck_dense",
     {
         "output_bottleneck_LayerNorm",
         "output_bottleneck_LayerNorm_weight",
         "",
         "output_bottleneck_dense",
     }},
    {"output_LayerNorm",
     {
         "output_bottleneck_dense",
         "output_bottleneck_dense_weight",
         "",
         "output_LayerNorm",
     }},
    {"output_dense",
     {
         "output_LayerNorm",
         "output_LayerNorm_weight",
         "",
         "output_dense",
     }},
    {"intermediate_dense",
     {
         "output_dense",
         "output_dense_weight",
         "",
         "intermediate_dense",
         "intermediate_dense",
     }},

    {"ffn_0_output_LayerNorm",
     {
         "intermediate_dense",
         "intermediate_dense_weight",
         "",
         "ffn_0_output_LayerNorm",
         "output_dense",
     }},
    {"ffn_0_output_dense",
     {
         "ffn_0_output_LayerNorm",
         "ffn_0_output_LayerNorm_weight",
         "",
         "ffn_0_output_dense",
     }},
    {"ffn_0_intermediate_dense",
     {
         "ffn_0_output_dense",
         "ffn_0_output_dense_weight",
         "",
         "ffn_0_intermediate_dense",
         "ffn_0_intermediate_dense",
     }},

    {"attention_output_LayerNorm",
     {
         "ffn_0_intermediate_dense",
         "ffn_0_intermediate_dense_weight",
         "",
         "attention_output_LayerNorm",
         "ffn_0_output_dense",
     }},
    {"attention_output_dense",
     {
         "attention_output_LayerNorm",
         "attention_output_LayerNorm_weight",
         "",
         "attention_output_dense",
     }},
    {"bottleneck_input_dense",
     {
         "attention_output_dense",
         "bottleneck_input_LayerNorm_weight",
         "",
         "bottleneck_input_dense",
     }},
    {"attention_self_context_layer",
     {
         "attention_output_dense",
         "attention_output_dense_weight",
         "",
         "attention_self_context_layer",
     }},

    {"attention_self_value_layer_0",
     {
         "attention_self_attention_probs_0",
         "attention_self_context_layer_0",
         "",
         "attention_self_value_layer_0",
     }},
    {"attention_self_value_layer_1",
     {
         "attention_self_attention_probs_1",
         "attention_self_context_layer_1",
         "",
         "attention_self_value_layer_1",
     }},
    {"attention_self_value_layer_2",
     {
         "attention_self_attention_probs_2",
         "attention_self_context_layer_2",
         "",
         "attention_self_value_layer_2",
     }},
    {"attention_self_value_layer_3",
     {
         "attention_self_attention_probs_3",
         "attention_self_context_layer_3",
         "",
         "attention_self_value_layer_3",
     }},

    {"attention_self_attention_probs_0",
     {
         "attention_self_context_layer_0",
         "attention_self_value_layer_0",
         "",
         "attention_self_attention_probs_0",
     }},
    {"attention_self_attention_probs_1",
     {
         "attention_self_context_layer_1",
         "attention_self_value_layer_1",
         "",
         "attention_self_attention_probs_1",
     }},
    {"attention_self_attention_probs_2",
     {
         "attention_self_context_layer_2",
         "attention_self_value_layer_2",
         "",
         "attention_self_attention_probs_2",
     }},
    {"attention_self_attention_probs_3",
     {
         "attention_self_context_layer_3",
         "attention_self_value_layer_3",
         "",
         "attention_self_attention_probs_3",
     }},

    {"attention_self_attention_scores_0",
     {
         "attention_self_attention_probs_0",
         "",
         "",
         "attention_self_attention_scores_0",
         "attention_self_attention_probs_0",
     }},
    {"attention_self_attention_scores_1",
     {
         "attention_self_attention_probs_1",
         "",
         "",
         "attention_self_attention_scores_1",
         "attention_self_attention_probs_1",
     }},
    {"attention_self_attention_scores_2",
     {
         "attention_self_attention_probs_2",
         "",
         "",
         "attention_self_attention_scores_2",
         "attention_self_attention_probs_2",
     }},
    {"attention_self_attention_scores_3",
     {
         "attention_self_attention_probs_3",
         "",
         "",
         "attention_self_attention_scores_3",
         "attention_self_attention_probs_3",
     }},

    {"attention_self_query_layer_0",
     {
         "attention_self_attention_scores_0",
         "attention_self_key_layer_0",
         "",
         "attention_self_query_layer_0",
     }},
    {"attention_self_query_layer_1",
     {
         "attention_self_attention_scores_1",
         "attention_self_key_layer_1",
         "",
         "attention_self_query_layer_1",
     }},
    {"attention_self_query_layer_2",
     {
         "attention_self_attention_scores_2",
         "attention_self_key_layer_2",
         "",
         "attention_self_query_layer_2",
     }},
    {"attention_self_query_layer_3",
     {
         "attention_self_attention_scores_3",
         "attention_self_key_layer_3",
         "",
         "attention_self_query_layer_3",
     }},

    {"attention_self_key_layer_0",
     {
         "attention_self_attention_scores_0",
         "attention_self_query_layer_0",
         "",
         "attention_self_key_layer_0",
     }},
    {"attention_self_key_layer_1",
     {
         "attention_self_attention_scores_1",
         "attention_self_query_layer_1",
         "",
         "attention_self_key_layer_1",
     }},
    {"attention_self_key_layer_2",
     {
         "attention_self_attention_scores_2",
         "attention_self_query_layer_2",
         "",
         "attention_self_key_layer_2",
     }},
    {"attention_self_key_layer_3",
     {
         "attention_self_attention_scores_3",
         "attention_self_query_layer_3",
         "",
         "attention_self_key_layer_3",
     }},

    {"query_to_bottleneck_attention_LayerNorm",
     {
         "attention_self_query_layer",
         "attention_self_query_weight",
         "",
         "bottleneck_attention_LayerNorm",
     }},
    {"key_to_bottleneck_attention_LayerNorm",
     {
         "attention_self_key_layer",
         "attention_self_key_weight",
         "",
         "bottleneck_attention_LayerNorm",
     }},
    {"bottleneck_attention_dense",
     {
         "bottleneck_attention_LayerNorm",
         "bottleneck_attention_LayerNorm_weight",
         "",
         "bottleneck_attention_dense",
     }},

    {"shared_attention_input_to_hidden_states",
     {
         "bottleneck_input_dense",
         "bottleneck_input_dense_weight",
         "",
         "hidden_states",
     }},
    {"value_to_hidden_states",
     {
         "attention_self_mixed_value_layer",
         "attention_self_value_weight",
         "",
         "hidden_states",
     }},
    {"bottlenecked_hidden_states",
     {
         "bottleneck_attention_dense",
         "bottleneck_attention_dense_weight",
         "",
         "hidden_states",
     }},
};
