#pragma once

#include <map>
#include <string>
#include <vector>

#include "test/common/VerificationTypes.h"

// (16 x 1) x (1 x 512)
const SimplifiedParams classifier_weight_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {1, 32, 1, 1, 1, 16}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = true,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (16 x 1)
const SimplifiedParams classifier_bias_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = true,
};

// (128 x 512) * (128 x 512)
const SimplifiedParams output_bottleneck_LayerNorm_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 1, 1, 1, 1, 1}, {32, 32, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = true,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (128 x 128) x (128 x 512)
const SimplifiedParams intermediate_dense_weight_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 1, 2, 1, 1, 1}, {8, 16, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (512 x 128) x (128 x 128)
const SimplifiedParams output_dense_weight_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{8, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (128 x 128) x (128 x 128)
const SimplifiedParams attention_output_dense_weight_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
    .CONCAT_INPUT = true,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (512 x 128) x (128 x 128)
const SimplifiedParams value_projection_weight_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{8, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = true,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (128 x 128) x (128 x 128)
const SimplifiedParams query_key_projection_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = true,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (128 x 128) * (128 x 128)
const SimplifiedParams input_bottleneck_LayerNorm_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{2, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = true,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0.0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = true,
};

// (512 x 128) x (128 x 128)
const SimplifiedParams input_bottleneck_weight_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{8, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 64}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = true,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
};

// (128 x 128)
const SimplifiedParams intra_bottleneck_bias_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = true,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0.0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = true,
};

// (128 x 128)
const SimplifiedParams intra_bottleneck_bias_with_head_concat = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = true,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = true,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0.0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = true,
};

// (128 x 512)
const SimplifiedParams inter_bottleneck_bias_gradient = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {8, 32, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = true,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = true,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0.0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = true,
};

std::map<std::string, SimplifiedParams> gradientParams;

gradientParams["classifier_weight"] = classifier_weight_gradient;
gradientParams["classifier_bias"] = classifier_bias_gradient;
gradientParams["output_bottleneck_LayerNorm_weight"] =
    output_bottleneck_LayerNorm_gradient;
gradientParams["output_bottleneck_LayerNorm_bias"] =
    inter_bottleneck_bias_gradient;
gradientParams["output_bottleneck_dense_weight"] =
    intermediate_dense_weight_gradient;
gradientParams["output_bottleneck_dense_bias"] = inter_bottleneck_bias_gradient;
gradientParams["output_LayerNorm_weight"] = input_bottleneck_LayerNorm_gradient;
gradientParams["output_LayerNorm_bias"] = intra_bottleneck_bias_gradient;
gradientParams["output_dense_weight"] = output_dense_weight_gradient;
gradientParams["output_dense_bias"] = intra_bottleneck_bias_gradient;
gradientParams["intermediate_dense_weight"] =
    intermediate_dense_weight_gradient;
gradientParams["intermediate_dense_bias"] = inter_bottleneck_bias_gradient;
gradientParams["ffn_0_output_LayerNorm_weight"] =
    input_bottleneck_LayerNorm_gradient;
gradientParams["ffn_0_output_LayerNorm_bias"] = intra_bottleneck_bias_gradient;
gradientParams["ffn_0_output_dense_weight"] = output_dense_weight_gradient;
gradientParams["ffn_0_output_dense_bias"] = intra_bottleneck_bias_gradient;
gradientParams["ffn_0_intermediate_dense_weight"] =
    intermediate_dense_weight_gradient;
gradientParams["ffn_0_intermediate_dense_bias"] =
    inter_bottleneck_bias_gradient;
gradientParams["attention_output_LayerNorm_weight"] =
    input_bottleneck_LayerNorm_gradient;
gradientParams["attention_output_LayerNorm_bias"] =
    intra_bottleneck_bias_gradient;
gradientParams["attention_output_dense_weight"] =
    attention_output_dense_weight_gradient;
gradientParams["attention_output_dense_bias"] = intra_bottleneck_bias_gradient;
gradientParams["attention_self_value_weight"] =
    value_projection_weight_gradient;
gradientParams["attention_self_value_bias"] =
    intra_bottleneck_bias_with_head_concat;
gradientParams["attention_self_query_weight"] = query_key_projection_weight;
gradientParams["attention_self_query_bias"] =
    intra_bottleneck_bias_with_head_concat;
gradientParams["attention_self_key_weight"] = query_key_projection_weight;
gradientParams["attention_self_key_bias"] =
    intra_bottleneck_bias_with_head_concat;
gradientParams["bottleneck_attention_LayerNorm_weight"] =
    input_bottleneck_LayerNorm_gradient;
gradientParams["bottleneck_attention_LayerNorm_bias"] =
    intra_bottleneck_bias_gradient;
gradientParams["bottleneck_attention_dense_weight"] =
    input_bottleneck_weight_gradient;
gradientParams["bottleneck_attention_dense_bias"] =
    intra_bottleneck_bias_gradient;
gradientParams["bottleneck_input_LayerNorm_weight"] =
    input_bottleneck_LayerNorm_gradient;
gradientParams["bottleneck_input_LayerNorm_bias"] =
    intra_bottleneck_bias_gradient;
gradientParams["bottleneck_input_dense_weight"] =
    input_bottleneck_weight_gradient;
gradientParams["bottleneck_input_dense_bias"] = intra_bottleneck_bias_gradient;

std::map<std::string, MemoryOffsets> gradientMemOffsets{
    {"classifier_weight",
     {
         0,
         4 * INTERMEDIATE_SIZE + 18 * INTRA_BOTTLENECK_SIZE,
         8 * INTERMEDIATE_SIZE + 5 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"classifier_bias",
     {
         0,
         0,
         8 * INTERMEDIATE_SIZE + 21 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_LayerNorm_weight",
     {
         3 * INTERMEDIATE_SIZE + 18 * INTRA_BOTTLENECK_SIZE,
         0,
         8 * INTERMEDIATE_SIZE + 3 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_LayerNorm_bias",
     {
         0,
         0,
         8 * INTERMEDIATE_SIZE + 4 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_dense_weight",
     {
         3 * INTERMEDIATE_SIZE + 17 * INTRA_BOTTLENECK_SIZE,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_dense_bias",
     {
         0,
         0,
         8 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"output_LayerNorm_weight",
     {
         3 * INTERMEDIATE_SIZE + 16 * INTRA_BOTTLENECK_SIZE,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 16 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_LayerNorm_bias",
     {
         0,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 17 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_dense_weight",
     {
         2 * INTERMEDIATE_SIZE + 16 * INTRA_BOTTLENECK_SIZE,
         0,
         6 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_dense_bias",
     {
         0,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"intermediate_dense_weight",
     {
         2 * INTERMEDIATE_SIZE + 15 * INTRA_BOTTLENECK_SIZE,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"intermediate_dense_bias",
     {
         0,
         0,
         6 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"ffn_0_output_LayerNorm_weight",
     {
         2 * INTERMEDIATE_SIZE + 14 * INTRA_BOTTLENECK_SIZE,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 13 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_output_LayerNorm_bias",
     {
         0,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 14 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_output_dense_weight",
     {
         INTERMEDIATE_SIZE + 14 * INTRA_BOTTLENECK_SIZE,
         0,
         4 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_output_dense_bias",
     {
         0,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_intermediate_dense_weight",
     {
         INTERMEDIATE_SIZE + 13 * INTRA_BOTTLENECK_SIZE,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_intermediate_dense_bias",
     {
         0,
         0,
         4 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"attention_output_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE + 12 * INTRA_BOTTLENECK_SIZE,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             10 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_output_LayerNorm_bias",
     {
         0,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             11 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_output_dense_weight",
     {
         INTERMEDIATE_SIZE + 11 * INTRA_BOTTLENECK_SIZE,
         0,
         3 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             9 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_output_dense_bias",
     {
         0,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             9 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"attention_self_value_weight",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             8 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_value_bias",
     {
         0,
         0,
         3 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             8 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_key_weight",
     {
         INTERMEDIATE_SIZE + 4 * INTRA_BOTTLENECK_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + INTRA_BOTTLENECK_SIZE +
             7 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_key_bias",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             7 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_query_weight",
     {
         INTERMEDIATE_SIZE + 4 * INTRA_BOTTLENECK_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + 6 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_query_bias",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + INTRA_BOTTLENECK_SIZE +
             6 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"bottleneck_attention_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE + INTRA_BOTTLENECK_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + 4 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_attention_LayerNorm_bias",
     {

         0,
         0,
         2 * INTERMEDIATE_SIZE + 5 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_attention_dense_weight",
     {
         0,
         0,
         INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_attention_dense_bias",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_input_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE,
         0,
         INTERMEDIATE_SIZE + INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_input_LayerNorm_bias",
     {
         0,
         0,
         INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_input_dense_weight",
     {
         0,
         0,
         0,
     }},
    {"bottleneck_input_dense_bias",
     {
         0,
         0,
         INTERMEDIATE_SIZE,
     }},
};

std::map<std::string, Files> gradientTestFiles{
    {"classifier_weight",
     {
         "classifier",
         "mobilebert_encoder_layer_20_output_bottleneck_LayerNorm",
         "",
         "classifier_weight",
     }},
    {"classifier_bias",
     {
         "classifier",
         "",
         "",
         "classifier_bias",
     }},
    {"output_bottleneck_LayerNorm_weight",
     {
         "output_bottleneck_dense",
         "output_bottleneck_LayerNorm",
         "",
         "output_bottleneck_LayerNorm_weight",
     }},
    {"output_bottleneck_LayerNorm_bias",
     {
         "",
         "output_bottleneck_LayerNorm",
         "",
         "output_bottleneck_LayerNorm_bias",
     }},
    {"output_bottleneck_dense_weight",
     {
         "output_LayerNorm",
         "output_bottleneck_dense",
         "",
         "output_bottleneck_dense_weight",
     }},
    {"output_bottleneck_dense_bias",
     {
         "",
         "output_bottleneck_dense",
         "",
         "output_bottleneck_dense_bias",
     }},

    {"output_LayerNorm_weight",
     {
         "output_dense",
         "output_LayerNorm",
         "",
         "output_LayerNorm_weight",
     }},
    {"output_LayerNorm_bias",
     {
         "",
         "output_LayerNorm",
         "",
         "output_LayerNorm_bias",
     }},
    {"output_dense_weight",
     {
         "intermediate_intermediate_act_fn",
         "output_dense",
         "",
         "output_dense_weight",
     }},
    {"output_dense_bias",
     {
         "",
         "output_dense",
         "",
         "output_dense_bias",
     }},
    {"intermediate_dense_weight",
     {
         "ffn_0_output_LayerNorm",
         "intermediate_dense",
         "",
         "intermediate_dense_weight",
     }},
    {"intermediate_dense_bias",
     {
         "",
         "intermediate_dense",
         "",
         "intermediate_dense_bias",
     }},

    {"ffn_0_output_LayerNorm_weight",
     {
         "ffn_0_output_dense",
         "ffn_0_output_LayerNorm",
         "",
         "ffn_0_output_LayerNorm_weight",
     }},
    {"ffn_0_output_LayerNorm_bias",
     {
         "",
         "ffn_0_output_LayerNorm",
         "",
         "ffn_0_output_LayerNorm_bias",
     }},
    {"ffn_0_output_dense_weight",
     {
         "ffn_0_intermediate_intermediate_act_fn",
         "ffn_0_output_dense",
         "",
         "ffn_0_output_dense_weight",
     }},
    {"ffn_0_output_dense_bias",
     {
         "",
         "ffn_0_output_dense",
         "",
         "ffn_0_output_dense_bias",
     }},
    {"ffn_0_intermediate_dense_weight",
     {
         "attention_output_LayerNorm",
         "ffn_0_intermediate_dense",
         "",
         "ffn_0_intermediate_dense_weight",
     }},
    {"ffn_0_intermediate_dense_bias",
     {
         "",
         "ffn_0_intermediate_dense",
         "",
         "ffn_0_intermediate_dense_bias",
     }},

    {"attention_output_LayerNorm_weight",
     {
         "attention_output_dense",
         "attention_output_LayerNorm",
         "",
         "attention_output_LayerNorm_weight",
     }},
    {"attention_output_LayerNorm_bias",
     {
         "",
         "attention_output_LayerNorm",
         "",
         "attention_output_LayerNorm_bias",
     }},
    {"attention_output_dense_weight",
     {
         "attention_self_context_layer",
         "attention_output_dense",
         "",
         "attention_output_dense_weight",
     }},
    {"attention_output_dense_bias",
     {
         "",
         "attention_output_dense",
         "",
         "attention_output_dense_bias",
     }},

    {"attention_self_value_weight",
     {
         "hidden_states",
         "attention_self_value_layer",
         "",
         "attention_self_value_weight",
     }},
    {"attention_self_value_bias",
     {
         "",
         "attention_self_value_layer",
         "",
         "attention_self_value_bias",
     }},
    {"attention_self_query_weight",
     {
         "bottleneck_attention_LayerNorm",
         "attention_self_query_layer",
         "",
         "attention_self_query_weight",
     }},
    {"attention_self_query_bias",
     {
         "",
         "attention_self_query_layer",
         "",
         "attention_self_query_bias",
     }},
    {"attention_self_key_weight",
     {
         "bottleneck_attention_LayerNorm",
         "attention_self_key_layer",
         "",
         "attention_self_key_weight",
     }},
    {"attention_self_key_bias",
     {
         "",
         "attention_self_key_layer",
         "",
         "attention_self_key_bias",
     }},

    {"bottleneck_attention_LayerNorm_weight",
     {
         "bottleneck_attention_dense",
         "bottleneck_attention_LayerNorm",
         "",
         "bottleneck_attention_LayerNorm_weight",
     }},
    {"bottleneck_attention_LayerNorm_bias",
     {
         "",
         "bottleneck_attention_LayerNorm",
         "",
         "bottleneck_attention_LayerNorm_bias",
     }},
    {"bottleneck_attention_dense_weight",
     {
         "hidden_states",
         "bottleneck_attention_dense",
         "",
         "bottleneck_attention_dense_weight",
     }},
    {"bottleneck_attention_dense_bias",
     {
         "",
         "bottleneck_attention_dense",
         "",
         "bottleneck_attention_dense_bias",
     }},

    {"bottleneck_input_LayerNorm_weight",
     {
         "bottleneck_input_dense",
         "bottleneck_input_LayerNorm",
         "",
         "bottleneck_input_LayerNorm_weight",
     }},
    {"bottleneck_input_LayerNorm_bias",
     {
         "",
         "bottleneck_input_LayerNorm",
         "",
         "bottleneck_input_LayerNorm_bias",
     }},
    {"bottleneck_input_dense_weight",
     {
         "hidden_states",
         "bottleneck_input_dense",
         "",
         "bottleneck_input_dense_weight",
     }},
    {"bottleneck_input_dense_bias",
     {
         "",
         "bottleneck_input_dense",
         "",
         "bottleneck_input_dense_bias",
     }},
};
