#pragma once

#include <map>
#include <string>
#include <vector>

#include "test/common/VerificationTypes.h"

// (16 x 512)
const SimplifiedParams classifier_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {32, 1, 1, 1, 1, 16}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 2e-2,
    .ACC_T_INPUT = true,
    .ACC_T_WEIGHT = true,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (16)
const SimplifiedParams classifier_bias = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 2e-2,
    .ACC_T_INPUT = true,
    .ACC_T_WEIGHT = true,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (512 x 128)
const SimplifiedParams input_bottleneck_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{16, 1, 1, 1, 1, 1}, {8, 1, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = false,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (128 x 512)
const SimplifiedParams intermediate_dense_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {32, 1, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = false,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (512)
const SimplifiedParams inter_bottleneck_bias = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {32, 1, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0,
    .ACC_T_INPUT = true,
    .ACC_T_WEIGHT = true,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (128 x 128)
const SimplifiedParams bottleneck_projection_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {8, 1, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0,
    .ACC_T_INPUT = false,
    .ACC_T_WEIGHT = false,
    .ACC_T_OUTPUT = false,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (128)
const SimplifiedParams intra_bottleneck_bias = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{1, 1, 1, 1, 1, 1}, {8, 1, 1, 1, 1, 1}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 0,
    .ACC_T_INPUT = true,
    .ACC_T_WEIGHT = true,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (128 x 16)
const SimplifiedParams lora_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{4, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 2e-2,
    .ACC_T_INPUT = true,
    .ACC_T_WEIGHT = true,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

// (512 x 16)
const SimplifiedParams value_lora_A_weight = {
    .INPUT_OFFSET = 0,
    .WEIGHT_OFFSET = 0,
    .OUTPUT_OFFSET = 0,
    .WEIGHT_TRANSPOSE = false,
    .loops = {{16, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 32}},
    .inputXLoopIndex = {0, 5},
    .inputYLoopIndex = {1, 4},
    .reductionLoopIndex = {3, 0},
    .weightLoopIndex = {2, 1},
    .fxIndex = 3,
    .fyIndex = 2,
    .weightReuseIndex = {4, 5},
    .STRIDE = 1,
    .REPLICATION = false,
    .RELU = false,
    .BIAS = false,
    .BIAS_OFFSET = 0,
    .RESIDUAL = false,
    .RESIDUAL_OFFSET = 0,
    .MAXPOOL = false,
    .AVGPOOL = false,
    .WEIGHT = false,
    .STORE_IN_ACC = false,
    .ACC_FROM_ACC = false,
    .SOFTMAX = false,
    .ATTENTION_SCALING = false,
    .FC = false,
    .NO_NORM = false,
    .SOFTMAX_GRAD = false,
    .FC_GRAD = false,
    .NO_NORM_GRAD = false,
    .RELU_GRAD = false,
    .BIAS_GRAD = false,
    .CROSS_ENTROPY_GRAD = false,
    .MSE_GRAD = false,
    .BCE_WITH_LOGITS_GRAD = false,
    .INPUT_TRANSPOSE = false,
    .CONCAT_INPUT = false,
    .CONCAT_WEIGHT = false,
    .SPLIT_OUTPUT = false,
    .GRAD_CLIPPING = false,
    .GRAD_CLIPPING_UNIT_TEST = false,
    .WEIGHT_SPLITTING = false,
    .WEIGHT_RESIDUAL_OFFSET = 0,
    .learningRate = 2e-2,
    .ACC_T_INPUT = true,
    .ACC_T_WEIGHT = true,
    .ACC_T_OUTPUT = true,
    .ACC_T_RESIDUAL = false,
    .outputExpBias = 0,
    .WEIGHT_UPDATE = true,
};

std::map<std::string, SimplifiedParams> weightParams;

weightParams["classifier_weight"] = classifier_weight;
weightParams["classifier_bias"] = classifier_bias;
weightParams["output_bottleneck_LayerNorm_weight"] = inter_bottleneck_bias;
weightParams["output_bottleneck_LayerNorm_bias"] = inter_bottleneck_bias;
weightParams["output_bottleneck_dense_weight"] = intermediate_dense_weight;
weightParams["output_bottleneck_dense_bias"] = inter_bottleneck_bias;
weightParams["output_LayerNorm_weight"] = intra_bottleneck_bias;
weightParams["output_LayerNorm_bias"] = intra_bottleneck_bias;
weightParams["output_dense_weight"] = input_bottleneck_weight;
weightParams["output_dense_bias"] = intra_bottleneck_bias;
weightParams["intermediate_dense_weight"] = intermediate_dense_weight;
weightParams["intermediate_dense_bias"] = inter_bottleneck_bias;
weightParams["ffn_0_output_LayerNorm_weight"] = intra_bottleneck_bias;
weightParams["ffn_0_output_LayerNorm_bias"] = intra_bottleneck_bias;
weightParams["ffn_0_output_dense_weight"] = input_bottleneck_weight;
weightParams["ffn_0_output_dense_bias"] = intra_bottleneck_bias;
weightParams["ffn_0_intermediate_dense_weight"] = intermediate_dense_weight;
weightParams["ffn_0_intermediate_dense_bias"] = inter_bottleneck_bias;
weightParams["attention_output_LayerNorm_weight"] = intra_bottleneck_bias;
weightParams["attention_output_LayerNorm_bias"] = intra_bottleneck_bias;
weightParams["attention_output_dense_weight"] = bottleneck_projection_weight;
weightParams["attention_output_dense_bias"] = intra_bottleneck_bias;
weightParams["attention_self_value_weight"] = bottleneck_projection_weight;
weightParams["attention_self_value_bias"] = intra_bottleneck_bias;
weightParams["attention_self_query_weight"] = bottleneck_projection_weight;
weightParams["attention_self_query_bias"] = intra_bottleneck_bias;
weightParams["attention_self_key_weight"] = bottleneck_projection_weight;
weightParams["attention_self_key_bias"] = intra_bottleneck_bias;
weightParams["bottleneck_attention_LayerNorm_weight"] = intra_bottleneck_bias;
weightParams["bottleneck_attention_LayerNorm_bias"] = intra_bottleneck_bias;
weightParams["bottleneck_attention_dense_weight"] = input_bottleneck_weight;
weightParams["bottleneck_attention_dense_bias"] = intra_bottleneck_bias;
weightParams["bottleneck_input_LayerNorm_weight"] = intra_bottleneck_bias;
weightParams["bottleneck_input_LayerNorm_bias"] = intra_bottleneck_bias;
weightParams["bottleneck_input_dense_weight"] = input_bottleneck_weight;
weightParams["bottleneck_input_dense_bias"] = intra_bottleneck_bias;
weightParams["attention_self_query_lora_A_weight"] = lora_weight;
weightParams["attention_self_query_lora_B_weight"] = lora_weight;
weightParams["attention_self_value_lora_A_weight"] = lora_weight;
weightParams["attention_self_value_lora_B_weight"] = value_lora_A_weight;

const std::map<std::string, MemoryOffsets> weightMemOffsets{
    {"classifier_weight",
     {
         0,
         4 * INTERMEDIATE_SIZE + 22 * INTRA_BOTTLENECK_SIZE,
         8 * INTERMEDIATE_SIZE + 5 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"classifier_bias",
     {
         0,
         0,
         8 * INTERMEDIATE_SIZE + 21 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_LayerNorm_weight",
     {
         3 * INTERMEDIATE_SIZE + 22 * INTRA_BOTTLENECK_SIZE,
         0,
         8 * INTERMEDIATE_SIZE + 3 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_LayerNorm_bias",
     {
         0,
         0,
         8 * INTERMEDIATE_SIZE + 4 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_dense_weight",
     {
         3 * INTERMEDIATE_SIZE + 21 * INTRA_BOTTLENECK_SIZE,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_bottleneck_dense_bias",
     {
         0,
         0,
         8 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 18 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"output_LayerNorm_weight",
     {
         3 * INTERMEDIATE_SIZE + 20 * INTRA_BOTTLENECK_SIZE,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 16 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_LayerNorm_bias",
     {
         0,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 17 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_dense_weight",
     {
         2 * INTERMEDIATE_SIZE + 20 * INTRA_BOTTLENECK_SIZE,
         0,
         6 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"output_dense_bias",
     {
         0,
         0,
         7 * INTERMEDIATE_SIZE + 2 * INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"intermediate_dense_weight",
     {
         2 * INTERMEDIATE_SIZE + 19 * INTRA_BOTTLENECK_SIZE,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"intermediate_dense_bias",
     {
         0,
         0,
         6 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 15 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"ffn_0_output_LayerNorm_weight",
     {
         2 * INTERMEDIATE_SIZE + 18 * INTRA_BOTTLENECK_SIZE,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 13 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_output_LayerNorm_bias",
     {
         0,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 14 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_output_dense_weight",
     {
         INTERMEDIATE_SIZE + 18 * INTRA_BOTTLENECK_SIZE,
         0,
         4 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_output_dense_bias",
     {
         0,
         0,
         5 * INTERMEDIATE_SIZE + INTERMEDIATE_BIAS_SIZE +
             3 * INTRA_BOTTLENECK_SIZE + 12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_intermediate_dense_weight",
     {
         INTERMEDIATE_SIZE + 17 * INTRA_BOTTLENECK_SIZE,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"ffn_0_intermediate_dense_bias",
     {
         0,
         0,
         4 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             12 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"attention_output_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE + 16 * INTRA_BOTTLENECK_SIZE,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             10 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_output_LayerNorm_bias",
     {
         0,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             11 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_output_dense_weight",
     {
         INTERMEDIATE_SIZE + 15 * INTRA_BOTTLENECK_SIZE,
         0,
         3 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             9 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_output_dense_bias",
     {
         0,
         0,
         3 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_SIZE +
             9 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"attention_self_value_weight",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             8 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_value_bias",
     {
         0,
         0,
         3 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             8 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_key_weight",
     {
         INTERMEDIATE_SIZE + 4 * INTRA_BOTTLENECK_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + INTRA_BOTTLENECK_SIZE +
             7 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_key_bias",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_SIZE +
             7 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_query_weight",
     {
         INTERMEDIATE_SIZE + 4 * INTRA_BOTTLENECK_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + 6 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"attention_self_query_bias",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + INTRA_BOTTLENECK_SIZE +
             6 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},

    {"bottleneck_attention_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE + INTRA_BOTTLENECK_SIZE,
         0,
         2 * INTERMEDIATE_SIZE + 4 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_attention_LayerNorm_bias",
     {

         0,
         0,
         2 * INTERMEDIATE_SIZE + 5 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_attention_dense_weight",
     {
         0,
         0,
         INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_attention_dense_bias",
     {
         0,
         0,
         2 * INTERMEDIATE_SIZE + 3 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_input_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE,
         0,
         INTERMEDIATE_SIZE + INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_input_LayerNorm_bias",
     {
         0,
         0,
         INTERMEDIATE_SIZE + 2 * INTRA_BOTTLENECK_BIAS_SIZE,
     }},
    {"bottleneck_input_dense_weight",
     {
         0,
         0,
         0,
     }},
    {"bottleneck_input_dense_bias",
     {
         0,
         0,
         INTERMEDIATE_SIZE,
     }},
};
