#pragma once

#include <map>
#include <string>
#include <vector>

#include "test/common/VerificationTypes.h"

std::map<std::string, std::string> weightParamsMapping{
    {"classifier_weight", "classifier_weight"},
    {"classifier_bias", "classifier_bias"},
    {"output_bottleneck_LayerNorm_weight", "intermediate_bias"},
    {"output_bottleneck_LayerNorm_bias", "intermediate_bias"},
    {"output_bottleneck_dense_weight", "intermediate"},
    {"output_bottleneck_dense_bias", "intermediate_bias"},
    {"output_LayerNorm_weight", "hidden_bias"},
    {"output_LayerNorm_bias", "hidden_bias"},
    {"output_dense_weight", "bottleneck"},
    {"output_dense_bias", "hidden_bias"},
    {"intermediate_dense_weight", "intermediate"},
    {"intermediate_dense_bias", "intermediate_bias"},
    {"ffn_0_output_LayerNorm_weight", "hidden_bias"},
    {"ffn_0_output_LayerNorm_bias", "hidden_bias"},
    {"ffn_0_output_dense_weight", "bottleneck"},
    {"ffn_0_output_dense_bias", "hidden_bias"},
    {"ffn_0_intermediate_dense_weight", "intermediate"},
    {"ffn_0_intermediate_dense_bias", "intermediate_bias"},
    {"attention_output_LayerNorm_weight", "hidden_bias"},
    {"attention_output_LayerNorm_bias", "hidden_bias"},
    {"attention_output_dense_weight", "hidden"},
    {"attention_output_dense_bias", "hidden_bias"},
    {"attention_self_value_weight", "hidden"},
    {"attention_self_value_bias", "hidden_bias"},
    {"attention_self_query_weight", "hidden"},
    {"attention_self_query_bias", "hidden_bias"},
    {"attention_self_key_weight", "hidden"},
    {"attention_self_key_bias", "hidden_bias"},
    {"bottleneck_attention_LayerNorm_weight", "hidden_bias"},
    {"bottleneck_attention_LayerNorm_bias", "hidden_bias"},
    {"bottleneck_attention_dense_weight", "bottleneck"},
    {"bottleneck_attention_dense_bias", "hidden_bias"},
    {"bottleneck_input_LayerNorm_weight", "hidden_bias"},
    {"bottleneck_input_LayerNorm_bias", "hidden_bias"},
    {"bottleneck_input_dense_weight", "bottleneck"},
    {"bottleneck_input_dense_bias", "hidden_bias"},
};

std::map<std::string, SimplifiedParams> weightParams{
    // (16 x 512)
    {"classifier_weight",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {1, 32, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},

    // (16)
    {"classifier_bias",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},

    // (512 x 128)
    {"bottleneck",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {32, 8, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},

    // (128 x 512)
    {"intermediate",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {8, 32, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},

    // (512)
    {"intermediate_bias",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {1, 32, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},

    // (128 x 128)
    {"hidden",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {8, 8, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},

    // (128)
    {"hidden_bias",
     {
         .INPUT_OFFSET = 0,
         .WEIGHT_OFFSET = 0,
         .OUTPUT_OFFSET = 0,
         .WEIGHT_TRANSPOSE = false,
         .loops = {{1, 1, 1, 1, 1, 1}, {1, 8, 1, 1, 1, 1}},
         .inputXLoopIndex = {0, 5},
         .inputYLoopIndex = {1, 4},
         .reductionLoopIndex = {3, 0},
         .weightLoopIndex = {2, 1},
         .fxIndex = 3,
         .fyIndex = 2,
         .weightReuseIndex = {4, 5},
         .STRIDE = 1,
         .REPLICATION = false,
         .RELU = false,
         .BIAS = false,
         .BIAS_OFFSET = 0,
         .RESIDUAL = false,
         .RESIDUAL_OFFSET = 0,
         .MAXPOOL = false,
         .AVGPOOL = false,
         .WEIGHT = false,
         .STORE_IN_ACC = false,
         .ACC_FROM_ACC = false,
         .SOFTMAX = false,
         .ATTENTION_MASK = false,
         .ATTENTION_SCALING = false,
         .FC = false,
         .NO_NORM = false,
         .SOFTMAX_GRAD = false,
         .FC_GRAD = false,
         .NO_NORM_GRAD = false,
         .RELU_GRAD = false,
         .BIAS_GRAD = false,
         .CROSS_ENTROPY_GRAD = false,
         .MSE_GRAD = false,
         .BCE_WITH_LOGITS_GRAD = false,
         .INPUT_TRANSPOSE = false,
         .CONCAT_INPUT = false,
         .CONCAT_WEIGHT = false,
         .SPLIT_OUTPUT = false,
         .GRAD_CLIPPING = false,
         .GRAD_CLIPPING_UNIT_TEST = false,
         .WEIGHT_SPLITTING = false,
         .WEIGHT_GRADIENT_OFFSET = 0,
         .BIAS_GRADIENT_OFFSET = 0,
         .learningRate = 3e-2,
         .ACC_T_INPUT = false,
         .ACC_T_WEIGHT = false,
         .ACC_T_OUTPUT = false,
         .WEIGHT_UPDATE = true,
     }},
};

std::map<std::string, MemoryOffsets> weightMemOffsets{
    {"classifier_weight",
     {
         0,
         4 * INTERMEDIATE_SIZE + 22 * HIDDEN_SIZE,
         8 * WEIGHT_INTERMEDIATE_SIZE + 5 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
     }},
    {"classifier_bias",
     {
         0,
         0,
         8 * WEIGHT_INTERMEDIATE_SIZE + 21 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
     }},
    {"output_bottleneck_LayerNorm_weight",
     {
         3 * INTERMEDIATE_SIZE + 22 * HIDDEN_SIZE,
         0,
         8 * WEIGHT_INTERMEDIATE_SIZE + 3 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
     }},
    {"output_bottleneck_LayerNorm_bias",
     {
         0,
         0,
         8 * WEIGHT_INTERMEDIATE_SIZE + 4 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
     }},
    {"output_bottleneck_dense_weight",
     {
         3 * INTERMEDIATE_SIZE + 21 * HIDDEN_SIZE,
         0,
         7 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
     }},
    {"output_bottleneck_dense_bias",
     {
         0,
         0,
         8 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 18 * BIAS_HIDDEN_SIZE,
     }},

    {"output_LayerNorm_weight",
     {
         3 * INTERMEDIATE_SIZE + 20 * HIDDEN_SIZE,
         0,
         7 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 16 * BIAS_HIDDEN_SIZE,
     }},
    {"output_LayerNorm_bias",
     {
         0,
         0,
         7 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 17 * BIAS_HIDDEN_SIZE,
     }},
    {"output_dense_weight",
     {
         2 * INTERMEDIATE_SIZE + 20 * HIDDEN_SIZE,
         0,
         6 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 15 * BIAS_HIDDEN_SIZE,
     }},
    {"output_dense_bias",
     {
         0,
         0,
         7 * WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 15 * BIAS_HIDDEN_SIZE,
     }},
    {"intermediate_dense_weight",
     {
         2 * INTERMEDIATE_SIZE + 19 * HIDDEN_SIZE,
         0,
         5 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 15 * BIAS_HIDDEN_SIZE,
     }},
    {"intermediate_dense_bias",
     {
         0,
         0,
         6 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 15 * BIAS_HIDDEN_SIZE,
     }},

    {"ffn_0_output_LayerNorm_weight",
     {
         2 * INTERMEDIATE_SIZE + 18 * HIDDEN_SIZE,
         0,
         5 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 13 * BIAS_HIDDEN_SIZE,
     }},
    {"ffn_0_output_LayerNorm_bias",
     {
         0,
         0,
         5 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 14 * BIAS_HIDDEN_SIZE,
     }},
    {"ffn_0_output_dense_weight",
     {
         INTERMEDIATE_SIZE + 18 * HIDDEN_SIZE,
         0,
         4 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 12 * BIAS_HIDDEN_SIZE,
     }},
    {"ffn_0_output_dense_bias",
     {
         0,
         0,
         5 * WEIGHT_INTERMEDIATE_SIZE + BIAS_INTERMEDIATE_SIZE +
             3 * WEIGHT_HIDDEN_SIZE + 12 * BIAS_HIDDEN_SIZE,
     }},
    {"ffn_0_intermediate_dense_weight",
     {
         INTERMEDIATE_SIZE + 17 * HIDDEN_SIZE,
         0,
         3 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             12 * BIAS_HIDDEN_SIZE,
     }},
    {"ffn_0_intermediate_dense_bias",
     {
         0,
         0,
         4 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             12 * BIAS_HIDDEN_SIZE,
     }},

    {"attention_output_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE + 16 * HIDDEN_SIZE,
         0,
         3 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             10 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_output_LayerNorm_bias",
     {
         0,
         0,
         3 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             11 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_output_dense_weight",
     {
         INTERMEDIATE_SIZE + 15 * HIDDEN_SIZE,
         0,
         3 * WEIGHT_INTERMEDIATE_SIZE + 2 * WEIGHT_HIDDEN_SIZE +
             9 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_output_dense_bias",
     {
         0,
         0,
         3 * WEIGHT_INTERMEDIATE_SIZE + 3 * WEIGHT_HIDDEN_SIZE +
             9 * BIAS_HIDDEN_SIZE,
     }},

    {"attention_self_value_weight",
     {
         0,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + 2 * WEIGHT_HIDDEN_SIZE +
             8 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_self_value_bias",
     {
         0,
         0,
         3 * WEIGHT_INTERMEDIATE_SIZE + 2 * WEIGHT_HIDDEN_SIZE +
             8 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_self_key_weight",
     {
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + WEIGHT_HIDDEN_SIZE +
             7 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_self_key_bias",
     {
         0,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + 2 * WEIGHT_HIDDEN_SIZE +
             7 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_self_query_weight",
     {
         INTERMEDIATE_SIZE + 4 * HIDDEN_SIZE,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + 6 * BIAS_HIDDEN_SIZE,
     }},
    {"attention_self_query_bias",
     {
         0,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + WEIGHT_HIDDEN_SIZE +
             6 * BIAS_HIDDEN_SIZE,
     }},

    {"bottleneck_attention_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE + HIDDEN_SIZE,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + 4 * BIAS_HIDDEN_SIZE,
     }},
    {"bottleneck_attention_LayerNorm_bias",
     {

         0,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + 5 * BIAS_HIDDEN_SIZE,
     }},
    {"bottleneck_attention_dense_weight",
     {
         0,
         0,
         WEIGHT_INTERMEDIATE_SIZE + 3 * BIAS_HIDDEN_SIZE,
     }},
    {"bottleneck_attention_dense_bias",
     {
         0,
         0,
         2 * WEIGHT_INTERMEDIATE_SIZE + 3 * BIAS_HIDDEN_SIZE,
     }},
    {"bottleneck_input_LayerNorm_weight",
     {
         INTERMEDIATE_SIZE,
         0,
         WEIGHT_INTERMEDIATE_SIZE + BIAS_HIDDEN_SIZE,
     }},
    {"bottleneck_input_LayerNorm_bias",
     {
         0,
         0,
         WEIGHT_INTERMEDIATE_SIZE + 2 * BIAS_HIDDEN_SIZE,
     }},
    {"bottleneck_input_dense_weight",
     {
         0,
         0,
         0,
     }},
    {"bottleneck_input_dense_bias",
     {
         0,
         0,
         WEIGHT_INTERMEDIATE_SIZE,
     }},
};
